-- RAG H2 兼容 schema
CREATE TABLE IF NOT EXISTS knowledge_base (
  id BIGINT AUTO_INCREMENT PRIMARY KEY,
  owner_id BIGINT NOT NULL,
  tenant_id BIGINT NOT NULL DEFAULT 0,
  name VARCHAR(128) NOT NULL,
  description VARCHAR(500),
  visibility VARCHAR(16) NOT NULL DEFAULT 'private',
  doc_count INT NOT NULL DEFAULT 0,
  chunk_count INT NOT NULL DEFAULT 0,
  tags VARCHAR(255),
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  deleted INT NOT NULL DEFAULT 0
);

CREATE TABLE IF NOT EXISTS document (
  id BIGINT AUTO_INCREMENT PRIMARY KEY,
  kb_id BIGINT NOT NULL,
  owner_id BIGINT NOT NULL,
  title VARCHAR(255) NOT NULL,
  source_type VARCHAR(16) NOT NULL DEFAULT 'txt',
  source_uri VARCHAR(500),
  content CLOB,
  size_bytes BIGINT NOT NULL DEFAULT 0,
  status VARCHAR(16) NOT NULL DEFAULT 'pending',
  error_msg VARCHAR(500),
  chunk_count INT NOT NULL DEFAULT 0,
  checksum VARCHAR(64),
  tags VARCHAR(255),
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  deleted INT NOT NULL DEFAULT 0
);

CREATE TABLE IF NOT EXISTS document_chunk (
  id BIGINT AUTO_INCREMENT PRIMARY KEY,
  doc_id BIGINT NOT NULL,
  kb_id BIGINT NOT NULL,
  owner_id BIGINT NOT NULL,
  chunk_index INT NOT NULL,
  content CLOB NOT NULL,
  embedding LONGVARBINARY NOT NULL,
  dim INT NOT NULL,
  char_count INT NOT NULL DEFAULT 0,
  start_pos INT NOT NULL DEFAULT 0,
  end_pos INT NOT NULL DEFAULT 0,
  access_count INT NOT NULL DEFAULT 0,
  last_access_at TIMESTAMP,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  deleted INT NOT NULL DEFAULT 0
);
