/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    ChatMessage: typeof import('./src/components/ChatMessage.vue')['default']
    CrossAppBinding: typeof import('./src/components/CrossAppBinding.vue')['default']
    LangSwitcher: typeof import('./src/components/LangSwitcher.vue')['default']
    MarkdownView: typeof import('./src/components/MarkdownView.vue')['default']
    MyWechat: typeof import('./src/components/MyWechat.vue')['default']
    PageContainer: typeof import('./src/components/PageContainer.vue')['default']
    PwaInstallPrompt: typeof import('./src/components/PwaInstallPrompt.vue')['default']
    PwaStatusBar: typeof import('./src/components/PwaStatusBar.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    StatCard: typeof import('./src/components/StatCard.vue')['default']
    StateBlock: typeof import('./src/components/StateBlock.vue')['default']
    WechatScanLogin: typeof import('./src/components/WechatScanLogin.vue')['default']
  }
}
