-- =====================================================
-- MiniMax Platform V3.5.8 - Database Schema (Auto-generated)
-- 77 tables from @TableName entity classes
-- Compatible: MySQL 8.0+ / MariaDB 10.6+ / H2 MODE=MySQL
-- Generated by: scripts/gen_complete_sql.py
-- =====================================================
SET NAMES utf8mb4;
SET FOREIGN_KEY_CHECKS=0;

CREATE TABLE IF NOT EXISTS `admin_audit_log` (
    `id` BIGINT NOT NULL AUTO_INCREMENT COMMENT '主键ID',
    `actor_id` VARCHAR(255) DEFAULT NULL COMMENT 'actor_id',
    `actor_name` VARCHAR(255) DEFAULT NULL COMMENT 'actor_name',
    `action` VARCHAR(255) DEFAULT NULL COMMENT 'action',
    `resource_type` VARCHAR(255) DEFAULT NULL COMMENT 'resource_type',
    `resource_id` VARCHAR(255) DEFAULT NULL COMMENT 'resource_id',
    `detail` VARCHAR(255) DEFAULT NULL COMMENT 'detail',
    `result` VARCHAR(255) DEFAULT NULL COMMENT 'result',
    `error_msg` VARCHAR(255) DEFAULT NULL COMMENT 'error_msg',
    `ip` VARCHAR(255) DEFAULT NULL COMMENT 'ip',
    `user_agent` VARCHAR(255) DEFAULT NULL COMMENT 'user_agent',
    `created_at` VARCHAR(255) DEFAULT NULL COMMENT 'created_at',
    PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS `audit_log_full` (
    `id` BIGINT NOT NULL AUTO_INCREMENT COMMENT '主键ID',
    `trace_id` VARCHAR(255) DEFAULT NULL COMMENT 'trace_id',
    `user_id` VARCHAR(255) DEFAULT NULL COMMENT 'user_id',
    `username` VARCHAR(255) DEFAULT NULL COMMENT 'username',
    `user_ip` VARCHAR(255) DEFAULT NULL COMMENT 'user_ip',
    `user_agent` VARCHAR(255) DEFAULT NULL COMMENT 'user_agent',
    `action` VARCHAR(255) DEFAULT NULL COMMENT 'action',
    `resource_type` VARCHAR(255) DEFAULT NULL COMMENT 'resource_type',
    `resource_id` VARCHAR(255) DEFAULT NULL COMMENT 'resource_id',
    `method` VARCHAR(255) DEFAULT NULL COMMENT 'method',
    `path` VARCHAR(255) DEFAULT NULL COMMENT 'path',
    `request_body` VARCHAR(255) DEFAULT NULL COMMENT 'request_body',
    `response_status` VARCHAR(255) DEFAULT NULL COMMENT 'response_status',
    `result` VARCHAR(255) DEFAULT NULL COMMENT 'result',
    `error_msg` VARCHAR(255) DEFAULT NULL COMMENT 'error_msg',
    `duration_ms` VARCHAR(255) DEFAULT NULL COMMENT 'duration_ms',
    `created_at` VARCHAR(255) DEFAULT NULL COMMENT 'created_at',
    PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS `agent_task` (
    `id` BIGINT NOT NULL AUTO_INCREMENT COMMENT '主键ID',
    `task_id` VARCHAR(255) DEFAULT NULL COMMENT 'task_id',
    `user_id` VARCHAR(255) DEFAULT NULL COMMENT 'user_id',
    `goal` VARCHAR(255) DEFAULT NULL COMMENT 'goal',
    `status` VARCHAR(255) DEFAULT NULL COMMENT 'status',
    `rounds` VARCHAR(255) DEFAULT NULL COMMENT 'rounds',
    `result` VARCHAR(255) DEFAULT NULL COMMENT 'result',
    `llm_calls` VARCHAR(255) DEFAULT NULL COMMENT 'llm_calls',
    `tool_calls` VARCHAR(255) DEFAULT NULL COMMENT 'tool_calls',
    `total_tokens` VARCHAR(255) DEFAULT NULL COMMENT 'total_tokens',
    `error_msg` VARCHAR(255) DEFAULT NULL COMMENT 'error_msg',
    `latency_ms` VARCHAR(255) DEFAULT NULL COMMENT 'latency_ms',
    `created_at` VARCHAR(255) DEFAULT NULL COMMENT 'created_at',
    `updated_at` VARCHAR(255) DEFAULT NULL COMMENT 'updated_at',
    `deleted` VARCHAR(255) DEFAULT NULL COMMENT 'deleted',
    PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS `collab_member` (
    `id` BIGINT NOT NULL AUTO_INCREMENT COMMENT '主键ID',
    `collab_id` VARCHAR(255) DEFAULT NULL COMMENT 'collab_id',
    `user_id` VARCHAR(255) DEFAULT NULL COMMENT 'user_id',
    `role` VARCHAR(255) DEFAULT NULL COMMENT 'role',
    `joined_at` VARCHAR(255) DEFAULT NULL COMMENT 'joined_at',
    `last_active_at` VARCHAR(255) DEFAULT NULL COMMENT 'last_active_at',
    PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS `collab_session` (
    `id` BIGINT NOT NULL AUTO_INCREMENT COMMENT '主键ID',
    `session_id` VARCHAR(255) DEFAULT NULL COMMENT 'session_id',
    `owner_id` VARCHAR(255) DEFAULT NULL COMMENT 'owner_id',
    `title` VARCHAR(255) DEFAULT NULL COMMENT 'title',
    `max_users` VARCHAR(255) DEFAULT NULL COMMENT 'max_users',
    `status` VARCHAR(255) DEFAULT NULL COMMENT 'status',
    `created_at` VARCHAR(255) DEFAULT NULL COMMENT 'created_at',
    `updated_at` VARCHAR(255) DEFAULT NULL COMMENT 'updated_at',
    `deleted` VARCHAR(255) DEFAULT NULL COMMENT 'deleted',
    PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS `kg_entity` (
    `id` BIGINT NOT NULL AUTO_INCREMENT COMMENT '主键ID',
    `user_id` VARCHAR(255) DEFAULT NULL COMMENT 'user_id',
    `name` VARCHAR(255) DEFAULT NULL COMMENT 'name',
    `entity_type` VARCHAR(255) DEFAULT NULL COMMENT 'entity_type',
    `description` VARCHAR(255) DEFAULT NULL COMMENT 'description',
    `aliases` VARCHAR(255) DEFAULT NULL COMMENT 'aliases',
    `importance` VARCHAR(255) DEFAULT NULL COMMENT 'importance',
    `source` VARCHAR(255) DEFAULT NULL COMMENT 'source',
    `ref_count` VARCHAR(255) DEFAULT NULL COMMENT 'ref_count',
    `created_at` VARCHAR(255) DEFAULT NULL COMMENT 'created_at',
    `updated_at` VARCHAR(255) DEFAULT NULL COMMENT 'updated_at',
    `deleted` VARCHAR(255) DEFAULT NULL COMMENT 'deleted',
    PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS `kg_relation` (
    `id` BIGINT NOT NULL AUTO_INCREMENT COMMENT '主键ID',
    `user_id` VARCHAR(255) DEFAULT NULL COMMENT 'user_id',
    `from_entity` VARCHAR(255) DEFAULT NULL COMMENT 'from_entity',
    `to_entity` VARCHAR(255) DEFAULT NULL COMMENT 'to_entity',
    `relation_type` VARCHAR(255) DEFAULT NULL COMMENT 'relation_type',
    `description` VARCHAR(255) DEFAULT NULL COMMENT 'description',
    `weight` VARCHAR(255) DEFAULT NULL COMMENT 'weight',
    `source` VARCHAR(255) DEFAULT NULL COMMENT 'source',
    `ref_count` VARCHAR(255) DEFAULT NULL COMMENT 'ref_count',
    `created_at` VARCHAR(255) DEFAULT NULL COMMENT 'created_at',
    `updated_at` VARCHAR(255) DEFAULT NULL COMMENT 'updated_at',
    `deleted` VARCHAR(255) DEFAULT NULL COMMENT 'deleted',
    PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS `plugin` (
    `id` BIGINT NOT NULL AUTO_INCREMENT COMMENT '主键ID',
    `name` VARCHAR(255) DEFAULT NULL COMMENT 'name',
    `display_name` VARCHAR(255) DEFAULT NULL COMMENT 'display_name',
    `description` VARCHAR(255) DEFAULT NULL COMMENT 'description',
    `version` VARCHAR(255) DEFAULT NULL COMMENT 'version',
    `author` VARCHAR(255) DEFAULT NULL COMMENT 'author',
    `category` VARCHAR(255) DEFAULT NULL COMMENT 'category',
    `scope` VARCHAR(255) DEFAULT NULL COMMENT 'scope',
    `owner_id` VARCHAR(255) DEFAULT NULL COMMENT 'owner_id',
    `icon` VARCHAR(255) DEFAULT NULL COMMENT 'icon',
    `entry` VARCHAR(255) DEFAULT NULL COMMENT 'entry',
    `plugin_type` VARCHAR(255) DEFAULT NULL COMMENT 'plugin_type',
    `config` VARCHAR(255) DEFAULT NULL COMMENT 'config',
    `enabled` VARCHAR(255) DEFAULT NULL COMMENT 'enabled',
    `downloads` VARCHAR(255) DEFAULT NULL COMMENT 'downloads',
    `rating` VARCHAR(255) DEFAULT NULL COMMENT 'rating',
    `created_at` VARCHAR(255) DEFAULT NULL COMMENT 'created_at',
    `updated_at` VARCHAR(255) DEFAULT NULL COMMENT 'updated_at',
    `deleted` VARCHAR(255) DEFAULT NULL COMMENT 'deleted',
    PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS `agent_group` (
    `id` BIGINT NOT NULL AUTO_INCREMENT COMMENT '主键ID',
    `group_id` VARCHAR(255) DEFAULT NULL COMMENT 'group_id',
    `name` VARCHAR(255) DEFAULT NULL COMMENT 'name',
    `description` VARCHAR(255) DEFAULT NULL COMMENT 'description',
    `strategy` VARCHAR(255) DEFAULT NULL COMMENT 'strategy',
    `members_json` VARCHAR(255) DEFAULT NULL COMMENT 'members_json',
    `status` VARCHAR(255) DEFAULT NULL COMMENT 'status',
    `owner_id` VARCHAR(255) DEFAULT NULL COMMENT 'owner_id',
    `tags` VARCHAR(255) DEFAULT NULL COMMENT 'tags',
    `last_run_at` VARCHAR(255) DEFAULT NULL COMMENT 'last_run_at',
    `run_count` VARCHAR(255) DEFAULT NULL COMMENT 'run_count',
    `created_at` VARCHAR(255) DEFAULT NULL COMMENT 'created_at',
    `updated_at` VARCHAR(255) DEFAULT NULL COMMENT 'updated_at',
    PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS `ai_chat_message` (
    `id` BIGINT NOT NULL AUTO_INCREMENT COMMENT '主键ID',
    `session_id` VARCHAR(255) DEFAULT NULL COMMENT 'session_id',
    `role` VARCHAR(255) DEFAULT NULL COMMENT 'role',
    `content` VARCHAR(255) DEFAULT NULL COMMENT 'content',
    `tool_code` VARCHAR(255) DEFAULT NULL COMMENT 'tool_code',
    `tool_input` VARCHAR(255) DEFAULT NULL COMMENT 'tool_input',
    `tool_output` VARCHAR(255) DEFAULT NULL COMMENT 'tool_output',
    `created_at` VARCHAR(255) DEFAULT NULL COMMENT 'created_at',
    PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS `ai_chat_session` (
    `id` BIGINT NOT NULL AUTO_INCREMENT COMMENT '主键ID',
    `session_id` VARCHAR(255) DEFAULT NULL COMMENT 'session_id',
    `user_id` VARCHAR(255) DEFAULT NULL COMMENT 'user_id',
    `username` VARCHAR(255) DEFAULT NULL COMMENT 'username',
    `title` VARCHAR(255) DEFAULT NULL COMMENT 'title',
    `created_at` VARCHAR(255) DEFAULT NULL COMMENT 'created_at',
    `updated_at` VARCHAR(255) DEFAULT NULL COMMENT 'updated_at',
    `deleted` VARCHAR(255) DEFAULT NULL COMMENT 'deleted',
    PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS `ai_generation_log` (
    `id` BIGINT NOT NULL AUTO_INCREMENT COMMENT '主键ID',
    `generation_id` VARCHAR(255) DEFAULT NULL COMMENT 'generation_id',
    `user_id` VARCHAR(255) DEFAULT NULL COMMENT 'user_id',
    `username` VARCHAR(255) DEFAULT NULL COMMENT 'username',
    `user_ip` VARCHAR(255) DEFAULT NULL COMMENT 'user_ip',
    `modality` VARCHAR(255) DEFAULT NULL COMMENT 'modality',
    `model_name` VARCHAR(255) DEFAULT NULL COMMENT 'model_name',
    `model_version` VARCHAR(255) DEFAULT NULL COMMENT 'model_version',
    `prompt` VARCHAR(255) DEFAULT NULL COMMENT 'prompt',
    `negative_prompt` VARCHAR(255) DEFAULT NULL COMMENT 'negative_prompt',
    `parameters` VARCHAR(255) DEFAULT NULL COMMENT 'parameters',
    `output_url` VARCHAR(255) DEFAULT NULL COMMENT 'output_url',
    `output_size` VARCHAR(255) DEFAULT NULL COMMENT 'output_size',
    `output_hash` VARCHAR(255) DEFAULT NULL COMMENT 'output_hash',
    `watermarked` VARCHAR(255) DEFAULT NULL COMMENT 'watermarked',
    `watermark_text` VARCHAR(255) DEFAULT NULL COMMENT 'watermark_text',
    `duration_ms` VARCHAR(255) DEFAULT NULL COMMENT 'duration_ms',
    `status` VARCHAR(255) DEFAULT NULL COMMENT 'status',
    `error_msg` VARCHAR(255) DEFAULT NULL COMMENT 'error_msg',
    `created_at` VARCHAR(255) DEFAULT NULL COMMENT 'created_at',
    PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS `ai_intent_keyword` (
    `id` BIGINT NOT NULL AUTO_INCREMENT COMMENT '主键ID',
    `intent` VARCHAR(255) DEFAULT NULL COMMENT 'intent',
    `keyword` VARCHAR(255) DEFAULT NULL COMMENT 'keyword',
    `weight` VARCHAR(255) DEFAULT NULL COMMENT 'weight',
    `is_regex` VARCHAR(255) DEFAULT NULL COMMENT 'is_regex',
    `enabled` VARCHAR(255) DEFAULT NULL COMMENT 'enabled',
    `language` VARCHAR(255) DEFAULT NULL COMMENT 'language',
    `remark` VARCHAR(255) DEFAULT NULL COMMENT 'remark',
    `created_at` VARCHAR(255) DEFAULT NULL COMMENT 'created_at',
    `updated_at` VARCHAR(255) DEFAULT NULL COMMENT 'updated_at',
    PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS `ai_tool` (
    `id` BIGINT NOT NULL AUTO_INCREMENT COMMENT '主键ID',
    `code` VARCHAR(255) DEFAULT NULL COMMENT 'code',
    `name` VARCHAR(255) DEFAULT NULL COMMENT 'name',
    `category` VARCHAR(255) DEFAULT NULL COMMENT 'category',
    `description` VARCHAR(255) DEFAULT NULL COMMENT 'description',
    `icon` VARCHAR(255) DEFAULT NULL COMMENT 'icon',
    `enabled` VARCHAR(255) DEFAULT NULL COMMENT 'enabled',
    `builtin` VARCHAR(255) DEFAULT NULL COMMENT 'builtin',
    `input_schema` VARCHAR(255) DEFAULT NULL COMMENT 'input_schema',
    `output_schema` VARCHAR(255) DEFAULT NULL COMMENT 'output_schema',
    `default_config` VARCHAR(255) DEFAULT NULL COMMENT 'default_config',
    `impl_type` VARCHAR(255) DEFAULT NULL COMMENT 'impl_type',
    `impl_value` VARCHAR(255) DEFAULT NULL COMMENT 'impl_value',
    `rate_limit` VARCHAR(255) DEFAULT NULL COMMENT 'rate_limit',
    `timeout_seconds` VARCHAR(255) DEFAULT NULL COMMENT 'timeout_seconds',
    `role_required` VARCHAR(255) DEFAULT NULL COMMENT 'role_required',
    `tags` VARCHAR(255) DEFAULT NULL COMMENT 'tags',
    `version` VARCHAR(255) DEFAULT NULL COMMENT 'version',
    `author` VARCHAR(255) DEFAULT NULL COMMENT 'author',
    `created_by` VARCHAR(255) DEFAULT NULL COMMENT 'created_by',
    `created_at` VARCHAR(255) DEFAULT NULL COMMENT 'created_at',
    `updated_at` VARCHAR(255) DEFAULT NULL COMMENT 'updated_at',
    `deleted` VARCHAR(255) DEFAULT NULL COMMENT 'deleted',
    PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS `ai_tool_invocation` (
    `id` BIGINT NOT NULL AUTO_INCREMENT COMMENT '主键ID',
    `tool_code` VARCHAR(255) DEFAULT NULL COMMENT 'tool_code',
    `user_id` VARCHAR(255) DEFAULT NULL COMMENT 'user_id',
    `username` VARCHAR(255) DEFAULT NULL COMMENT 'username',
    `input_json` VARCHAR(255) DEFAULT NULL COMMENT 'input_json',
    `output_json` VARCHAR(255) DEFAULT NULL COMMENT 'output_json',
    `status` VARCHAR(255) DEFAULT NULL COMMENT 'status',
    `error_message` VARCHAR(255) DEFAULT NULL COMMENT 'error_message',
    `duration_ms` VARCHAR(255) DEFAULT NULL COMMENT 'duration_ms',
    `ip` VARCHAR(255) DEFAULT NULL COMMENT 'ip',
    `user_agent` VARCHAR(255) DEFAULT NULL COMMENT 'user_agent',
    `data_source_id` VARCHAR(255) DEFAULT NULL COMMENT 'data_source_id',
    `created_at` VARCHAR(255) DEFAULT NULL COMMENT 'created_at',
    PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS `audit_log` (
    `id` BIGINT NOT NULL AUTO_INCREMENT COMMENT '主键ID',
    `trace_id` VARCHAR(255) DEFAULT NULL COMMENT 'trace_id',
    `user_id` VARCHAR(255) DEFAULT NULL COMMENT 'user_id',
    `username` VARCHAR(255) DEFAULT NULL COMMENT 'username',
    `user_ip` VARCHAR(255) DEFAULT NULL COMMENT 'user_ip',
    `user_agent` VARCHAR(255) DEFAULT NULL COMMENT 'user_agent',
    `action` VARCHAR(255) DEFAULT NULL COMMENT 'action',
    `resource_type` VARCHAR(255) DEFAULT NULL COMMENT 'resource_type',
    `resource_id` VARCHAR(255) DEFAULT NULL COMMENT 'resource_id',
    `method` VARCHAR(255) DEFAULT NULL COMMENT 'method',
    `path` VARCHAR(255) DEFAULT NULL COMMENT 'path',
    `request_body` VARCHAR(255) DEFAULT NULL COMMENT 'request_body',
    `response_status` VARCHAR(255) DEFAULT NULL COMMENT 'response_status',
    `result` VARCHAR(255) DEFAULT NULL COMMENT 'result',
    `error_msg` VARCHAR(255) DEFAULT NULL COMMENT 'error_msg',
    `duration_ms` VARCHAR(255) DEFAULT NULL COMMENT 'duration_ms',
    `created_at` VARCHAR(255) DEFAULT NULL COMMENT 'created_at',
    PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS `billing_record` (
    `id` BIGINT NOT NULL AUTO_INCREMENT COMMENT '主键ID',
    `record_id` VARCHAR(255) DEFAULT NULL COMMENT 'record_id',
    `user_id` VARCHAR(255) DEFAULT NULL COMMENT 'user_id',
    `license_id` VARCHAR(255) DEFAULT NULL COMMENT 'license_id',
    `model_entry_id` VARCHAR(255) DEFAULT NULL COMMENT 'model_entry_id',
    `record_type` VARCHAR(255) DEFAULT NULL COMMENT 'record_type',
    `amount_cents` VARCHAR(255) DEFAULT NULL COMMENT 'amount_cents',
    `currency` VARCHAR(255) DEFAULT NULL COMMENT 'currency',
    `status` VARCHAR(255) DEFAULT NULL COMMENT 'status',
    `payment_method` VARCHAR(255) DEFAULT NULL COMMENT 'payment_method',
    `external_transaction_id` VARCHAR(255) DEFAULT NULL COMMENT 'external_transaction_id',
    `description` VARCHAR(255) DEFAULT NULL COMMENT 'description',
    `created_at` VARCHAR(255) DEFAULT NULL COMMENT 'created_at',
    `updated_at` VARCHAR(255) DEFAULT NULL COMMENT 'updated_at',
    PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS `cluster_node` (
    `id` BIGINT NOT NULL AUTO_INCREMENT COMMENT '主键ID',
    `node_id` VARCHAR(255) DEFAULT NULL COMMENT 'node_id',
    `name` VARCHAR(255) DEFAULT NULL COMMENT 'name',
    `address` VARCHAR(255) DEFAULT NULL COMMENT 'address',
    `region` VARCHAR(255) DEFAULT NULL COMMENT 'region',
    `zone` VARCHAR(255) DEFAULT NULL COMMENT 'zone',
    `capabilities` VARCHAR(255) DEFAULT NULL COMMENT 'capabilities',
    `total_cores` VARCHAR(255) DEFAULT NULL COMMENT 'total_cores',
    `total_memory_mb` VARCHAR(255) DEFAULT NULL COMMENT 'total_memory_mb',
    `total_gpus` VARCHAR(255) DEFAULT NULL COMMENT 'total_gpus',
    `cpu_usage` VARCHAR(255) DEFAULT NULL COMMENT 'cpu_usage',
    `memory_usage` VARCHAR(255) DEFAULT NULL COMMENT 'memory_usage',
    `gpu_usage` VARCHAR(255) DEFAULT NULL COMMENT 'gpu_usage',
    `active_tasks` VARCHAR(255) DEFAULT NULL COMMENT 'active_tasks',
    `status` VARCHAR(255) DEFAULT NULL COMMENT 'status',
    `is_leader` VARCHAR(255) DEFAULT NULL COMMENT 'is_leader',
    `last_heartbeat` VARCHAR(255) DEFAULT NULL COMMENT 'last_heartbeat',
    `started_at` VARCHAR(255) DEFAULT NULL COMMENT 'started_at',
    `created_at` VARCHAR(255) DEFAULT NULL COMMENT 'created_at',
    `updated_at` VARCHAR(255) DEFAULT NULL COMMENT 'updated_at',
    PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS `dashboard_metric` (
    `id` BIGINT NOT NULL AUTO_INCREMENT COMMENT '主键ID',
    `metric` VARCHAR(255) DEFAULT NULL COMMENT 'metric',
    `dimension` VARCHAR(255) DEFAULT NULL COMMENT 'dimension',
    `value` VARCHAR(255) DEFAULT NULL COMMENT 'value',
    `tags` VARCHAR(255) DEFAULT NULL COMMENT 'tags',
    `timestamp` VARCHAR(255) DEFAULT NULL COMMENT 'timestamp',
    PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS `data_source` (
    `id` BIGINT NOT NULL AUTO_INCREMENT COMMENT '主键ID',
    `name` VARCHAR(255) DEFAULT NULL COMMENT 'name',
    `type` VARCHAR(255) DEFAULT NULL COMMENT 'type',
    `jdbc_url` VARCHAR(255) DEFAULT NULL COMMENT 'jdbc_url',
    `username` VARCHAR(255) DEFAULT NULL COMMENT 'username',
    `password` VARCHAR(255) DEFAULT NULL COMMENT 'password',
    `driver_class` VARCHAR(255) DEFAULT NULL COMMENT 'driver_class',
    `pool_size` VARCHAR(255) DEFAULT NULL COMMENT 'pool_size',
    `min_idle` VARCHAR(255) DEFAULT NULL COMMENT 'min_idle',
    `max_lifetime` VARCHAR(255) DEFAULT NULL COMMENT 'max_lifetime',
    `enabled` VARCHAR(255) DEFAULT NULL COMMENT 'enabled',
    `test_status` VARCHAR(255) DEFAULT NULL COMMENT 'test_status',
    `test_message` VARCHAR(255) DEFAULT NULL COMMENT 'test_message',
    `last_test_at` VARCHAR(255) DEFAULT NULL COMMENT 'last_test_at',
    `description` VARCHAR(255) DEFAULT NULL COMMENT 'description',
    `tags` VARCHAR(255) DEFAULT NULL COMMENT 'tags',
    `created_by` VARCHAR(255) DEFAULT NULL COMMENT 'created_by',
    `created_at` VARCHAR(255) DEFAULT NULL COMMENT 'created_at',
    `updated_at` VARCHAR(255) DEFAULT NULL COMMENT 'updated_at',
    `deleted` VARCHAR(255) DEFAULT NULL COMMENT 'deleted',
    PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS `kb_chunk` (
    `id` BIGINT NOT NULL AUTO_INCREMENT COMMENT '主键ID',
    `chunk_id` VARCHAR(255) DEFAULT NULL COMMENT 'chunk_id',
    `doc_id` VARCHAR(255) DEFAULT NULL COMMENT 'doc_id',
    `kb_id` VARCHAR(255) DEFAULT NULL COMMENT 'kb_id',
    `seq` VARCHAR(255) DEFAULT NULL COMMENT 'seq',
    `content` VARCHAR(255) DEFAULT NULL COMMENT 'content',
    `char_count` VARCHAR(255) DEFAULT NULL COMMENT 'char_count',
    `token_count` VARCHAR(255) DEFAULT NULL COMMENT 'token_count',
    `embedding` VARCHAR(255) DEFAULT NULL COMMENT 'embedding',
    `embedding_model` VARCHAR(255) DEFAULT NULL COMMENT 'embedding_model',
    `keywords` VARCHAR(255) DEFAULT NULL COMMENT 'keywords',
    `summary` VARCHAR(255) DEFAULT NULL COMMENT 'summary',
    `location` VARCHAR(255) DEFAULT NULL COMMENT 'location',
    `created_at` VARCHAR(255) DEFAULT NULL COMMENT 'created_at',
    PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS `kb_document` (
    `id` BIGINT NOT NULL AUTO_INCREMENT COMMENT '主键ID',
    `doc_id` VARCHAR(255) DEFAULT NULL COMMENT 'doc_id',
    `kb_id` VARCHAR(255) DEFAULT NULL COMMENT 'kb_id',
    `filename` VARCHAR(255) DEFAULT NULL COMMENT 'filename',
    `mime_type` VARCHAR(255) DEFAULT NULL COMMENT 'mime_type',
    `size_bytes` VARCHAR(255) DEFAULT NULL COMMENT 'size_bytes',
    `sha256` VARCHAR(255) DEFAULT NULL COMMENT 'sha256',
    `file_path` VARCHAR(255) DEFAULT NULL COMMENT 'file_path',
    `source` VARCHAR(255) DEFAULT NULL COMMENT 'source',
    `source_url` VARCHAR(255) DEFAULT NULL COMMENT 'source_url',
    `status` VARCHAR(255) DEFAULT NULL COMMENT 'status',
    `chunk_count` VARCHAR(255) DEFAULT NULL COMMENT 'chunk_count',
    `embedding_count` VARCHAR(255) DEFAULT NULL COMMENT 'embedding_count',
    `error` VARCHAR(255) DEFAULT NULL COMMENT 'error',
    `tags` VARCHAR(255) DEFAULT NULL COMMENT 'tags',
    `owner_id` VARCHAR(255) DEFAULT NULL COMMENT 'owner_id',
    `is_public` VARCHAR(255) DEFAULT NULL COMMENT 'is_public',
    `created_at` VARCHAR(255) DEFAULT NULL COMMENT 'created_at',
    `updated_at` VARCHAR(255) DEFAULT NULL COMMENT 'updated_at',
    PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS `kb_permission` (
    `id` BIGINT NOT NULL AUTO_INCREMENT COMMENT '主键ID',
    `kb_id` VARCHAR(255) DEFAULT NULL COMMENT 'kb_id',
    `subject_type` VARCHAR(255) DEFAULT NULL COMMENT 'subject_type',
    `subject_id` VARCHAR(255) DEFAULT NULL COMMENT 'subject_id',
    `permission` VARCHAR(255) DEFAULT NULL COMMENT 'permission',
    `grant_by` VARCHAR(255) DEFAULT NULL COMMENT 'grant_by',
    `created_at` VARCHAR(255) DEFAULT NULL COMMENT 'created_at',
    PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS `raft_log` (
    `id` BIGINT NOT NULL AUTO_INCREMENT COMMENT '主键ID',
    `term` VARCHAR(255) DEFAULT NULL COMMENT 'term',
    `log_index` VARCHAR(255) DEFAULT NULL COMMENT 'log_index',
    `node_id` VARCHAR(255) DEFAULT NULL COMMENT 'node_id',
    `command` VARCHAR(255) DEFAULT NULL COMMENT 'command',
    `committed` VARCHAR(255) DEFAULT NULL COMMENT 'committed',
    `committed_at` VARCHAR(255) DEFAULT NULL COMMENT 'committed_at',
    `created_at` VARCHAR(255) DEFAULT NULL COMMENT 'created_at',
    PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS `model_license` (
    `id` BIGINT NOT NULL AUTO_INCREMENT COMMENT '主键ID',
    `license_key` VARCHAR(255) DEFAULT NULL COMMENT 'license_key',
    `model_entry_id` VARCHAR(255) DEFAULT NULL COMMENT 'model_entry_id',
    `model_version_id` VARCHAR(255) DEFAULT NULL COMMENT 'model_version_id',
    `user_id` VARCHAR(255) DEFAULT NULL COMMENT 'user_id',
    `license_type` VARCHAR(255) DEFAULT NULL COMMENT 'license_type',
    `status` VARCHAR(255) DEFAULT NULL COMMENT 'status',
    `quota_calls` VARCHAR(255) DEFAULT NULL COMMENT 'quota_calls',
    `used_calls` VARCHAR(255) DEFAULT NULL COMMENT 'used_calls',
    `start_at` VARCHAR(255) DEFAULT NULL COMMENT 'start_at',
    `expire_at` VARCHAR(255) DEFAULT NULL COMMENT 'expire_at',
    `price_cents` VARCHAR(255) DEFAULT NULL COMMENT 'price_cents',
    `created_at` VARCHAR(255) DEFAULT NULL COMMENT 'created_at',
    `updated_at` VARCHAR(255) DEFAULT NULL COMMENT 'updated_at',
    PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS `model_version` (
    `id` BIGINT NOT NULL AUTO_INCREMENT COMMENT '主键ID',
    `version_id` VARCHAR(255) DEFAULT NULL COMMENT 'version_id',
    `model_entry_id` VARCHAR(255) DEFAULT NULL COMMENT 'model_entry_id',
    `version` VARCHAR(255) DEFAULT NULL COMMENT 'version',
    `changelog` VARCHAR(255) DEFAULT NULL COMMENT 'changelog',
    `file_path` VARCHAR(255) DEFAULT NULL COMMENT 'file_path',
    `size_bytes` VARCHAR(255) DEFAULT NULL COMMENT 'size_bytes',
    `sha256` VARCHAR(255) DEFAULT NULL COMMENT 'sha256',
    `input_schema` VARCHAR(255) DEFAULT NULL COMMENT 'input_schema',
    `output_schema` VARCHAR(255) DEFAULT NULL COMMENT 'output_schema',
    `status` VARCHAR(255) DEFAULT NULL COMMENT 'status',
    `is_latest` VARCHAR(255) DEFAULT NULL COMMENT 'is_latest',
    `uploader_id` VARCHAR(255) DEFAULT NULL COMMENT 'uploader_id',
    `backward_compatible` VARCHAR(255) DEFAULT NULL COMMENT 'backward_compatible',
    `metadata` VARCHAR(255) DEFAULT NULL COMMENT 'metadata',
    `created_at` VARCHAR(255) DEFAULT NULL COMMENT 'created_at',
    `updated_at` VARCHAR(255) DEFAULT NULL COMMENT 'updated_at',
    PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS `moderation_record` (
    `id` BIGINT NOT NULL AUTO_INCREMENT COMMENT '主键ID',
    `trace_id` VARCHAR(255) DEFAULT NULL COMMENT 'trace_id',
    `user_id` VARCHAR(255) DEFAULT NULL COMMENT 'user_id',
    `username` VARCHAR(255) DEFAULT NULL COMMENT 'username',
    `content_type` VARCHAR(255) DEFAULT NULL COMMENT 'content_type',
    `content_hash` VARCHAR(255) DEFAULT NULL COMMENT 'content_hash',
    `content_size` VARCHAR(255) DEFAULT NULL COMMENT 'content_size',
    `content_url` VARCHAR(255) DEFAULT NULL COMMENT 'content_url',
    `moderation_status` VARCHAR(255) DEFAULT NULL COMMENT 'moderation_status',
    `risk_level` VARCHAR(255) DEFAULT NULL COMMENT 'risk_level',
    `risk_labels` VARCHAR(255) DEFAULT NULL COMMENT 'risk_labels',
    `risk_score` VARCHAR(255) DEFAULT NULL COMMENT 'risk_score',
    `moderator` VARCHAR(255) DEFAULT NULL COMMENT 'moderator',
    `rejection_reason` VARCHAR(255) DEFAULT NULL COMMENT 'rejection_reason',
    `created_at` VARCHAR(255) DEFAULT NULL COMMENT 'created_at',
    PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS `multimedia_file` (
    `id` BIGINT NOT NULL AUTO_INCREMENT COMMENT '主键ID',
    `file_id` VARCHAR(255) DEFAULT NULL COMMENT 'file_id',
    `user_id` VARCHAR(255) DEFAULT NULL COMMENT 'user_id',
    `username` VARCHAR(255) DEFAULT NULL COMMENT 'username',
    `file_name` VARCHAR(255) DEFAULT NULL COMMENT 'file_name',
    `original_name` VARCHAR(255) DEFAULT NULL COMMENT 'original_name',
    `file_type` VARCHAR(255) DEFAULT NULL COMMENT 'file_type',
    `mime_type` VARCHAR(255) DEFAULT NULL COMMENT 'mime_type',
    `file_size` VARCHAR(255) DEFAULT NULL COMMENT 'file_size',
    `file_hash` VARCHAR(255) DEFAULT NULL COMMENT 'file_hash',
    `storage_path` VARCHAR(255) DEFAULT NULL COMMENT 'storage_path',
    `storage_type` VARCHAR(255) DEFAULT NULL COMMENT 'storage_type',
    `encrypted` VARCHAR(255) DEFAULT NULL COMMENT 'encrypted',
    `duration_ms` VARCHAR(255) DEFAULT NULL COMMENT 'duration_ms',
    `width` VARCHAR(255) DEFAULT NULL COMMENT 'width',
    `height` VARCHAR(255) DEFAULT NULL COMMENT 'height',
    `bitrate` VARCHAR(255) DEFAULT NULL COMMENT 'bitrate',
    `sample_rate` VARCHAR(255) DEFAULT NULL COMMENT 'sample_rate',
    `channels` VARCHAR(255) DEFAULT NULL COMMENT 'channels',
    `codec` VARCHAR(255) DEFAULT NULL COMMENT 'codec',
    `exif` VARCHAR(255) DEFAULT NULL COMMENT 'exif',
    `moderation_status` VARCHAR(255) DEFAULT NULL COMMENT 'moderation_status',
    `moderation_id` VARCHAR(255) DEFAULT NULL COMMENT 'moderation_id',
    `watermarked` VARCHAR(255) DEFAULT NULL COMMENT 'watermarked',
    `is_public` VARCHAR(255) DEFAULT NULL COMMENT 'is_public',
    `access_count` VARCHAR(255) DEFAULT NULL COMMENT 'access_count',
    `expire_at` VARCHAR(255) DEFAULT NULL COMMENT 'expire_at',
    `created_at` VARCHAR(255) DEFAULT NULL COMMENT 'created_at',
    PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS `pipeline_log` (
    `id` BIGINT NOT NULL AUTO_INCREMENT COMMENT '主键ID',
    `session_id` VARCHAR(255) DEFAULT NULL COMMENT 'session_id',
    `user_id` VARCHAR(255) DEFAULT NULL COMMENT 'user_id',
    `client_ip` VARCHAR(255) DEFAULT NULL COMMENT 'client_ip',
    `input_text` VARCHAR(255) DEFAULT NULL COMMENT 'input_text',
    `input_modality` VARCHAR(255) DEFAULT NULL COMMENT 'input_modality',
    `intent` VARCHAR(255) DEFAULT NULL COMMENT 'intent',
    `output_text` VARCHAR(255) DEFAULT NULL COMMENT 'output_text',
    `output_tokens` VARCHAR(255) DEFAULT NULL COMMENT 'output_tokens',
    `compute_device` VARCHAR(255) DEFAULT NULL COMMENT 'compute_device',
    `compute_mode` VARCHAR(255) DEFAULT NULL COMMENT 'compute_mode',
    `total_cost_ms` VARCHAR(255) DEFAULT NULL COMMENT 'total_cost_ms',
    `stage_costs` VARCHAR(255) DEFAULT NULL COMMENT 'stage_costs',
    `risk_level` VARCHAR(255) DEFAULT NULL COMMENT 'risk_level',
    `needs_review` VARCHAR(255) DEFAULT NULL COMMENT 'needs_review',
    `rag_hits` VARCHAR(255) DEFAULT NULL COMMENT 'rag_hits',
    `tool_calls` VARCHAR(255) DEFAULT NULL COMMENT 'tool_calls',
    `error_message` VARCHAR(255) DEFAULT NULL COMMENT 'error_message',
    `created_at` VARCHAR(255) DEFAULT NULL COMMENT 'created_at',
    PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS `push_message` (
    `id` BIGINT NOT NULL AUTO_INCREMENT COMMENT '主键ID',
    `message_id` VARCHAR(255) DEFAULT NULL COMMENT 'message_id',
    `title` VARCHAR(255) DEFAULT NULL COMMENT 'title',
    `body` VARCHAR(255) DEFAULT NULL COMMENT 'body',
    `icon` VARCHAR(255) DEFAULT NULL COMMENT 'icon',
    `click_action` VARCHAR(255) DEFAULT NULL COMMENT 'click_action',
    `data` VARCHAR(255) DEFAULT NULL COMMENT 'data',
    `target_type` VARCHAR(255) DEFAULT NULL COMMENT 'target_type',
    `target_value` VARCHAR(255) DEFAULT NULL COMMENT 'target_value',
    `status` VARCHAR(255) DEFAULT NULL COMMENT 'status',
    `success_count` VARCHAR(255) DEFAULT NULL COMMENT 'success_count',
    `failure_count` VARCHAR(255) DEFAULT NULL COMMENT 'failure_count',
    `error` VARCHAR(255) DEFAULT NULL COMMENT 'error',
    `created_at` VARCHAR(255) DEFAULT NULL COMMENT 'created_at',
    `updated_at` VARCHAR(255) DEFAULT NULL COMMENT 'updated_at',
    PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS `push_subscription` (
    `id` BIGINT NOT NULL AUTO_INCREMENT COMMENT '主键ID',
    `subscription_id` VARCHAR(255) DEFAULT NULL COMMENT 'subscription_id',
    `user_id` VARCHAR(255) DEFAULT NULL COMMENT 'user_id',
    `platform` VARCHAR(255) DEFAULT NULL COMMENT 'platform',
    `endpoint` VARCHAR(255) DEFAULT NULL COMMENT 'endpoint',
    `p256dh_key` VARCHAR(255) DEFAULT NULL COMMENT 'p256dh_key',
    `auth_key` VARCHAR(255) DEFAULT NULL COMMENT 'auth_key',
    `user_agent` VARCHAR(255) DEFAULT NULL COMMENT 'user_agent',
    `status` VARCHAR(255) DEFAULT NULL COMMENT 'status',
    `last_active_at` VARCHAR(255) DEFAULT NULL COMMENT 'last_active_at',
    `created_at` VARCHAR(255) DEFAULT NULL COMMENT 'created_at',
    `updated_at` VARCHAR(255) DEFAULT NULL COMMENT 'updated_at',
    PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS `sensitive_word` (
    `id` BIGINT NOT NULL AUTO_INCREMENT COMMENT '主键ID',
    `word` VARCHAR(255) DEFAULT NULL COMMENT 'word',
    `category` VARCHAR(255) DEFAULT NULL COMMENT 'category',
    `level` VARCHAR(255) DEFAULT NULL COMMENT 'level',
    `action` VARCHAR(255) DEFAULT NULL COMMENT 'action',
    `enabled` VARCHAR(255) DEFAULT NULL COMMENT 'enabled',
    `created_at` VARCHAR(255) DEFAULT NULL COMMENT 'created_at',
    PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS `training_checkpoint` (
    `id` BIGINT NOT NULL AUTO_INCREMENT COMMENT '主键ID',
    `task_id` VARCHAR(255) DEFAULT NULL COMMENT 'task_id',
    `checkpoint_id` VARCHAR(255) DEFAULT NULL COMMENT 'checkpoint_id',
    `name` VARCHAR(255) DEFAULT NULL COMMENT 'name',
    `epoch` VARCHAR(255) DEFAULT NULL COMMENT 'epoch',
    `step` VARCHAR(255) DEFAULT NULL COMMENT 'step',
    `file_path` VARCHAR(255) DEFAULT NULL COMMENT 'file_path',
    `size_bytes` VARCHAR(255) DEFAULT NULL COMMENT 'size_bytes',
    `sha256` VARCHAR(255) DEFAULT NULL COMMENT 'sha256',
    `val_loss` VARCHAR(255) DEFAULT NULL COMMENT 'val_loss',
    `accuracy` VARCHAR(255) DEFAULT NULL COMMENT 'accuracy',
    `tags` VARCHAR(255) DEFAULT NULL COMMENT 'tags',
    `metadata` VARCHAR(255) DEFAULT NULL COMMENT 'metadata',
    `created_at` VARCHAR(255) DEFAULT NULL COMMENT 'created_at',
    PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS `training_job` (
    `id` BIGINT NOT NULL AUTO_INCREMENT COMMENT '主键ID',
    `task_id` VARCHAR(255) DEFAULT NULL COMMENT 'task_id',
    `name` VARCHAR(255) DEFAULT NULL COMMENT 'name',
    `model` VARCHAR(255) DEFAULT NULL COMMENT 'model',
    `status` VARCHAR(255) DEFAULT NULL COMMENT 'status',
    `total_epochs` VARCHAR(255) DEFAULT NULL COMMENT 'total_epochs',
    `current_epoch` VARCHAR(255) DEFAULT NULL COMMENT 'current_epoch',
    `current_step` VARCHAR(255) DEFAULT NULL COMMENT 'current_step',
    `start_time_ms` VARCHAR(255) DEFAULT NULL COMMENT 'start_time_ms',
    `end_time_ms` VARCHAR(255) DEFAULT NULL COMMENT 'end_time_ms',
    `config` VARCHAR(255) DEFAULT NULL COMMENT 'config',
    `error` VARCHAR(255) DEFAULT NULL COMMENT 'error',
    `owner_id` VARCHAR(255) DEFAULT NULL COMMENT 'owner_id',
    `tags` VARCHAR(255) DEFAULT NULL COMMENT 'tags',
    `last_loss` VARCHAR(255) DEFAULT NULL COMMENT 'last_loss',
    `last_val_loss` VARCHAR(255) DEFAULT NULL COMMENT 'last_val_loss',
    `last_accuracy` VARCHAR(255) DEFAULT NULL COMMENT 'last_accuracy',
    `total_steps` VARCHAR(255) DEFAULT NULL COMMENT 'total_steps',
    `created_at` VARCHAR(255) DEFAULT NULL COMMENT 'created_at',
    `updated_at` VARCHAR(255) DEFAULT NULL COMMENT 'updated_at',
    PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS `training_metric` (
    `id` BIGINT NOT NULL AUTO_INCREMENT COMMENT '主键ID',
    `task_id` VARCHAR(255) DEFAULT NULL COMMENT 'task_id',
    `epoch` VARCHAR(255) DEFAULT NULL COMMENT 'epoch',
    `step` VARCHAR(255) DEFAULT NULL COMMENT 'step',
    `loss` VARCHAR(255) DEFAULT NULL COMMENT 'loss',
    `val_loss` VARCHAR(255) DEFAULT NULL COMMENT 'val_loss',
    `accuracy` VARCHAR(255) DEFAULT NULL COMMENT 'accuracy',
    `learning_rate` VARCHAR(255) DEFAULT NULL COMMENT 'learning_rate',
    `elapsed_ms` VARCHAR(255) DEFAULT NULL COMMENT 'elapsed_ms',
    `timestamp` VARCHAR(255) DEFAULT NULL COMMENT 'timestamp',
    PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS `analytics_datasource` (
    `id` BIGINT NOT NULL AUTO_INCREMENT COMMENT '主键ID',
    `user_id` VARCHAR(255) DEFAULT NULL COMMENT 'user_id',
    `name` VARCHAR(255) DEFAULT NULL COMMENT 'name',
    `type` VARCHAR(255) DEFAULT NULL COMMENT 'type',
    `jdbc_url` VARCHAR(255) DEFAULT NULL COMMENT 'jdbc_url',
    `username` VARCHAR(255) DEFAULT NULL COMMENT 'username',
    `password_enc` VARCHAR(255) DEFAULT NULL COMMENT 'password_enc',
    `description` VARCHAR(255) DEFAULT NULL COMMENT 'description',
    `deleted` VARCHAR(255) DEFAULT NULL COMMENT 'deleted',
    `created_at` VARCHAR(255) DEFAULT NULL COMMENT 'created_at',
    `updated_at` VARCHAR(255) DEFAULT NULL COMMENT 'updated_at',
    PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS `analytics_ingest_task` (
    `id` BIGINT NOT NULL AUTO_INCREMENT COMMENT '主键ID',
    `user_id` VARCHAR(255) DEFAULT NULL COMMENT 'user_id',
    `task_id` VARCHAR(255) DEFAULT NULL COMMENT 'task_id',
    `filename` VARCHAR(255) DEFAULT NULL COMMENT 'filename',
    `file_type` VARCHAR(255) DEFAULT NULL COMMENT 'file_type',
    `encoding` VARCHAR(255) DEFAULT NULL COMMENT 'encoding',
    `separator` VARCHAR(255) DEFAULT NULL COMMENT 'separator',
    `file_size` VARCHAR(255) DEFAULT NULL COMMENT 'file_size',
    `status` VARCHAR(255) DEFAULT NULL COMMENT 'status',
    `error_message` VARCHAR(255) DEFAULT NULL COMMENT 'error_message',
    `quality_json` VARCHAR(255) DEFAULT NULL COMMENT 'quality_json',
    `total_rows` VARCHAR(255) DEFAULT NULL COMMENT 'total_rows',
    `total_columns` VARCHAR(255) DEFAULT NULL COMMENT 'total_columns',
    `columns_json` VARCHAR(255) DEFAULT NULL COMMENT 'columns_json',
    `created_at` VARCHAR(255) DEFAULT NULL COMMENT 'created_at',
    `finished_at` VARCHAR(255) DEFAULT NULL COMMENT 'finished_at',
    PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS `analytics_nlsql_history` (
    `id` BIGINT NOT NULL AUTO_INCREMENT COMMENT '主键ID',
    `user_id` VARCHAR(255) DEFAULT NULL COMMENT 'user_id',
    `data_source_id` VARCHAR(255) DEFAULT NULL COMMENT 'data_source_id',
    `question` VARCHAR(255) DEFAULT NULL COMMENT 'question',
    `generated_sql` VARCHAR(255) DEFAULT NULL COMMENT 'generated_sql',
    `corrected_sql` VARCHAR(255) DEFAULT NULL COMMENT 'corrected_sql',
    `model` VARCHAR(255) DEFAULT NULL COMMENT 'model',
    `prompt_tokens` VARCHAR(255) DEFAULT NULL COMMENT 'prompt_tokens',
    `completion_tokens` VARCHAR(255) DEFAULT NULL COMMENT 'completion_tokens',
    `duration_ms` VARCHAR(255) DEFAULT NULL COMMENT 'duration_ms',
    `success` VARCHAR(255) DEFAULT NULL COMMENT 'success',
    `error_message` VARCHAR(255) DEFAULT NULL COMMENT 'error_message',
    `feedback_rating` VARCHAR(255) DEFAULT NULL COMMENT 'feedback_rating',
    `created_at` VARCHAR(255) DEFAULT NULL COMMENT 'created_at',
    PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS `analytics_report` (
    `id` BIGINT NOT NULL AUTO_INCREMENT COMMENT '主键ID',
    `user_id` VARCHAR(255) DEFAULT NULL COMMENT 'user_id',
    `report_id` VARCHAR(255) DEFAULT NULL COMMENT 'report_id',
    `title` VARCHAR(255) DEFAULT NULL COMMENT 'title',
    `question` VARCHAR(255) DEFAULT NULL COMMENT 'question',
    `sql_text` VARCHAR(255) DEFAULT NULL COMMENT 'sql_text',
    `markdown` VARCHAR(255) DEFAULT NULL COMMENT 'markdown',
    `chart_options_json` VARCHAR(255) DEFAULT NULL COMMENT 'chart_options_json',
    `row_count` VARCHAR(255) DEFAULT NULL COMMENT 'row_count',
    `duration_ms` VARCHAR(255) DEFAULT NULL COMMENT 'duration_ms',
    `format` VARCHAR(255) DEFAULT NULL COMMENT 'format',
    `created_at` VARCHAR(255) DEFAULT NULL COMMENT 'created_at',
    PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS `auth_login_log` (
    `id` BIGINT NOT NULL AUTO_INCREMENT COMMENT '主键ID',
    `user_id` VARCHAR(255) DEFAULT NULL COMMENT 'user_id',
    `username` VARCHAR(255) DEFAULT NULL COMMENT 'username',
    `ip` VARCHAR(255) DEFAULT NULL COMMENT 'ip',
    `user_agent` VARCHAR(255) DEFAULT NULL COMMENT 'user_agent',
    `status` VARCHAR(255) DEFAULT NULL COMMENT 'status',
    `message` VARCHAR(255) DEFAULT NULL COMMENT 'message',
    `created_at` VARCHAR(255) DEFAULT NULL COMMENT 'created_at',
    PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS `auth_refresh_token` (
    `id` BIGINT NOT NULL AUTO_INCREMENT COMMENT '主键ID',
    `user_id` VARCHAR(255) DEFAULT NULL COMMENT 'user_id',
    `token` VARCHAR(255) DEFAULT NULL COMMENT 'token',
    `expires_at` VARCHAR(255) DEFAULT NULL COMMENT 'expires_at',
    `revoked` VARCHAR(255) DEFAULT NULL COMMENT 'revoked',
    `created_at` VARCHAR(255) DEFAULT NULL COMMENT 'created_at',
    PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS `notification` (
    `id` BIGINT NOT NULL AUTO_INCREMENT COMMENT '主键ID',
    `user_id` VARCHAR(255) DEFAULT NULL COMMENT 'user_id',
    `type` VARCHAR(255) DEFAULT NULL COMMENT 'type',
    `title` VARCHAR(255) DEFAULT NULL COMMENT 'title',
    `content` VARCHAR(255) DEFAULT NULL COMMENT 'content',
    `is_read` VARCHAR(255) DEFAULT NULL COMMENT 'is_read',
    `created_at` VARCHAR(255) DEFAULT NULL COMMENT 'created_at',
    `updated_at` VARCHAR(255) DEFAULT NULL COMMENT 'updated_at',
    PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS `oauth_app_config` (
    `id` BIGINT NOT NULL AUTO_INCREMENT COMMENT '主键ID',
    `platform` VARCHAR(255) DEFAULT NULL COMMENT 'platform',
    `app_type` VARCHAR(255) DEFAULT NULL COMMENT 'app_type',
    `app_id` VARCHAR(255) DEFAULT NULL COMMENT 'app_id',
    `app_secret` VARCHAR(255) DEFAULT NULL COMMENT 'app_secret',
    `public_key` VARCHAR(255) DEFAULT NULL COMMENT 'public_key',
    `redirect_uri` VARCHAR(255) DEFAULT NULL COMMENT 'redirect_uri',
    `scopes` VARCHAR(255) DEFAULT NULL COMMENT 'scopes',
    `enabled` VARCHAR(255) DEFAULT NULL COMMENT 'enabled',
    `extra_config` VARCHAR(255) DEFAULT NULL COMMENT 'extra_config',
    `created_at` VARCHAR(255) DEFAULT NULL COMMENT 'created_at',
    `updated_at` VARCHAR(255) DEFAULT NULL COMMENT 'updated_at',
    PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS `oauth_binding` (
    `id` BIGINT NOT NULL AUTO_INCREMENT COMMENT '主键ID',
    `user_id` VARCHAR(255) DEFAULT NULL COMMENT 'user_id',
    `platform` VARCHAR(255) DEFAULT NULL COMMENT 'platform',
    `app_type` VARCHAR(255) DEFAULT NULL COMMENT 'app_type',
    `openid` VARCHAR(255) DEFAULT NULL COMMENT 'openid',
    `unionid` VARCHAR(255) DEFAULT NULL COMMENT 'unionid',
    `nickname` VARCHAR(255) DEFAULT NULL COMMENT 'nickname',
    `avatar` VARCHAR(255) DEFAULT NULL COMMENT 'avatar',
    `access_token` VARCHAR(255) DEFAULT NULL COMMENT 'access_token',
    `refresh_token` VARCHAR(255) DEFAULT NULL COMMENT 'refresh_token',
    `token_expires_at` VARCHAR(255) DEFAULT NULL COMMENT 'token_expires_at',
    `raw_data` VARCHAR(255) DEFAULT NULL COMMENT 'raw_data',
    `bound_at` VARCHAR(255) DEFAULT NULL COMMENT 'bound_at',
    `last_login_at` VARCHAR(255) DEFAULT NULL COMMENT 'last_login_at',
    PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS `sys_role` (
    `id` BIGINT NOT NULL AUTO_INCREMENT COMMENT '主键ID',
    `code` VARCHAR(255) DEFAULT NULL COMMENT 'code',
    `name` VARCHAR(255) DEFAULT NULL COMMENT 'name',
    `description` VARCHAR(255) DEFAULT NULL COMMENT 'description',
    `sort` VARCHAR(255) DEFAULT NULL COMMENT 'sort',
    `enabled` VARCHAR(255) DEFAULT NULL COMMENT 'enabled',
    `created_at` VARCHAR(255) DEFAULT NULL COMMENT 'created_at',
    `updated_at` VARCHAR(255) DEFAULT NULL COMMENT 'updated_at',
    `deleted` VARCHAR(255) DEFAULT NULL COMMENT 'deleted',
    PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS `sys_user` (
    `id` BIGINT NOT NULL AUTO_INCREMENT COMMENT '主键ID',
    `username` VARCHAR(255) DEFAULT NULL COMMENT 'username',
    `password` VARCHAR(255) DEFAULT NULL COMMENT 'password',
    `nickname` VARCHAR(255) DEFAULT NULL COMMENT 'nickname',
    `email` VARCHAR(255) DEFAULT NULL COMMENT 'email',
    `phone` VARCHAR(255) DEFAULT NULL COMMENT 'phone',
    `avatar` VARCHAR(255) DEFAULT NULL COMMENT 'avatar',
    `gender` VARCHAR(255) DEFAULT NULL COMMENT 'gender',
    `status` VARCHAR(255) DEFAULT NULL COMMENT 'status',
    `last_login_ip` VARCHAR(255) DEFAULT NULL COMMENT 'last_login_ip',
    `last_login_at` VARCHAR(255) DEFAULT NULL COMMENT 'last_login_at',
    `tenant_id` VARCHAR(255) DEFAULT NULL COMMENT 'tenant_id',
    `remark` VARCHAR(255) DEFAULT NULL COMMENT 'remark',
    `wechat_openid` VARCHAR(255) DEFAULT NULL COMMENT 'wechat_openid',
    `wechat_unionid` VARCHAR(255) DEFAULT NULL COMMENT 'wechat_unionid',
    `wechat_nickname` VARCHAR(255) DEFAULT NULL COMMENT 'wechat_nickname',
    `wechat_avatar` VARCHAR(255) DEFAULT NULL COMMENT 'wechat_avatar',
    `wechat_bound_at` VARCHAR(255) DEFAULT NULL COMMENT 'wechat_bound_at',
    `qq_openid` VARCHAR(255) DEFAULT NULL COMMENT 'qq_openid',
    `qq_unionid` VARCHAR(255) DEFAULT NULL COMMENT 'qq_unionid',
    `qq_nickname` VARCHAR(255) DEFAULT NULL COMMENT 'qq_nickname',
    `qq_avatar` VARCHAR(255) DEFAULT NULL COMMENT 'qq_avatar',
    `qq_bound_at` VARCHAR(255) DEFAULT NULL COMMENT 'qq_bound_at',
    `alipay_openid` VARCHAR(255) DEFAULT NULL COMMENT 'alipay_openid',
    `alipay_user_id` VARCHAR(255) DEFAULT NULL COMMENT 'alipay_user_id',
    `alipay_nickname` VARCHAR(255) DEFAULT NULL COMMENT 'alipay_nickname',
    `alipay_avatar` VARCHAR(255) DEFAULT NULL COMMENT 'alipay_avatar',
    `alipay_bound_at` VARCHAR(255) DEFAULT NULL COMMENT 'alipay_bound_at',
    `created_by` VARCHAR(255) DEFAULT NULL COMMENT 'created_by',
    `created_at` VARCHAR(255) DEFAULT NULL COMMENT 'created_at',
    `updated_by` VARCHAR(255) DEFAULT NULL COMMENT 'updated_by',
    `updated_at` VARCHAR(255) DEFAULT NULL COMMENT 'updated_at',
    `deleted` VARCHAR(255) DEFAULT NULL COMMENT 'deleted',
    PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS `sys_user_role` (
    `user_id` BIGINT DEFAULT NULL COMMENT 'user_id',
    `role_id` BIGINT DEFAULT NULL COMMENT 'role_id',
    PRIMARY KEY (`user_id`, `role_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='sys_user_role (auto-generated V3.5.9)';

CREATE TABLE IF NOT EXISTS `tenant` (
    `id` BIGINT NOT NULL AUTO_INCREMENT COMMENT '主键ID',
    `code` VARCHAR(255) DEFAULT NULL COMMENT 'code',
    `name` VARCHAR(255) DEFAULT NULL COMMENT 'name',
    `plan` VARCHAR(255) DEFAULT NULL COMMENT 'plan',
    `status` VARCHAR(255) DEFAULT NULL COMMENT 'status',
    `max_users` VARCHAR(255) DEFAULT NULL COMMENT 'max_users',
    `max_models` VARCHAR(255) DEFAULT NULL COMMENT 'max_models',
    `qps_limit` VARCHAR(255) DEFAULT NULL COMMENT 'qps_limit',
    `monthly_quota` VARCHAR(255) DEFAULT NULL COMMENT 'monthly_quota',
    `used_quota` VARCHAR(255) DEFAULT NULL COMMENT 'used_quota',
    `expire_at` VARCHAR(255) DEFAULT NULL COMMENT 'expire_at',
    `contact_email` VARCHAR(255) DEFAULT NULL COMMENT 'contact_email',
    `contact_phone` VARCHAR(255) DEFAULT NULL COMMENT 'contact_phone',
    `remark` VARCHAR(255) DEFAULT NULL COMMENT 'remark',
    `created_at` VARCHAR(255) DEFAULT NULL COMMENT 'created_at',
    `updated_at` VARCHAR(255) DEFAULT NULL COMMENT 'updated_at',
    `deleted` VARCHAR(255) DEFAULT NULL COMMENT 'deleted',
    PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS `unionid_relations` (
    `id` BIGINT NOT NULL AUTO_INCREMENT COMMENT '主键ID',
    `user_id` VARCHAR(255) DEFAULT NULL COMMENT 'user_id',
    `unionid` VARCHAR(255) DEFAULT NULL COMMENT 'unionid',
    `platform` VARCHAR(255) DEFAULT NULL COMMENT 'platform',
    `first_seen_at` VARCHAR(255) DEFAULT NULL COMMENT 'first_seen_at',
    `last_seen_at` VARCHAR(255) DEFAULT NULL COMMENT 'last_seen_at',
    `binding_count` VARCHAR(255) DEFAULT NULL COMMENT 'binding_count',
    PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS `user_api_key` (
    `id` BIGINT NOT NULL AUTO_INCREMENT COMMENT '主键ID',
    `user_id` VARCHAR(255) DEFAULT NULL COMMENT 'user_id',
    `name` VARCHAR(255) DEFAULT NULL COMMENT 'name',
    `key_hash` VARCHAR(255) DEFAULT NULL COMMENT 'key_hash',
    `key_prefix` VARCHAR(255) DEFAULT NULL COMMENT 'key_prefix',
    `scopes` VARCHAR(255) DEFAULT NULL COMMENT 'scopes',
    `expires_at` VARCHAR(255) DEFAULT NULL COMMENT 'expires_at',
    `last_used_at` VARCHAR(255) DEFAULT NULL COMMENT 'last_used_at',
    `use_count` VARCHAR(255) DEFAULT NULL COMMENT 'use_count',
    `enabled` VARCHAR(255) DEFAULT NULL COMMENT 'enabled',
    `created_at` VARCHAR(255) DEFAULT NULL COMMENT 'created_at',
    `updated_at` VARCHAR(255) DEFAULT NULL COMMENT 'updated_at',
    `deleted` VARCHAR(255) DEFAULT NULL COMMENT 'deleted',
    PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS `wechat_config` (
    `id` BIGINT NOT NULL AUTO_INCREMENT COMMENT '主键ID',
    `app_type` VARCHAR(255) DEFAULT NULL COMMENT 'app_type',
    `app_id` VARCHAR(255) DEFAULT NULL COMMENT 'app_id',
    `app_secret` VARCHAR(255) DEFAULT NULL COMMENT 'app_secret',
    `token` VARCHAR(255) DEFAULT NULL COMMENT 'token',
    `aes_key` VARCHAR(255) DEFAULT NULL COMMENT 'aes_key',
    `redirect_uri` VARCHAR(255) DEFAULT NULL COMMENT 'redirect_uri',
    `scope` VARCHAR(255) DEFAULT NULL COMMENT 'scope',
    `enabled` VARCHAR(255) DEFAULT NULL COMMENT 'enabled',
    `remark` VARCHAR(255) DEFAULT NULL COMMENT 'remark',
    `created_at` VARCHAR(255) DEFAULT NULL COMMENT 'created_at',
    `updated_at` VARCHAR(255) DEFAULT NULL COMMENT 'updated_at',
    PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS `wechat_scan_session` (
    `id` BIGINT NOT NULL AUTO_INCREMENT COMMENT '主键ID',
    `ticket` VARCHAR(255) DEFAULT NULL COMMENT 'ticket',
    `scene_id` VARCHAR(255) DEFAULT NULL COMMENT 'scene_id',
    `status` VARCHAR(255) DEFAULT NULL COMMENT 'status',
    `openid` VARCHAR(255) DEFAULT NULL COMMENT 'openid',
    `unionid` VARCHAR(255) DEFAULT NULL COMMENT 'unionid',
    `nickname` VARCHAR(255) DEFAULT NULL COMMENT 'nickname',
    `avatar` VARCHAR(255) DEFAULT NULL COMMENT 'avatar',
    `user_id` VARCHAR(255) DEFAULT NULL COMMENT 'user_id',
    `access_token` VARCHAR(255) DEFAULT NULL COMMENT 'access_token',
    `refresh_token` VARCHAR(255) DEFAULT NULL COMMENT 'refresh_token',
    `client_ip` VARCHAR(255) DEFAULT NULL COMMENT 'client_ip',
    `user_agent` VARCHAR(255) DEFAULT NULL COMMENT 'user_agent',
    `expires_at` VARCHAR(255) DEFAULT NULL COMMENT 'expires_at',
    `confirmed_at` VARCHAR(255) DEFAULT NULL COMMENT 'confirmed_at',
    `created_at` VARCHAR(255) DEFAULT NULL COMMENT 'created_at',
    `updated_at` VARCHAR(255) DEFAULT NULL COMMENT 'updated_at',
    PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS `wechat_user_binding` (
    `id` BIGINT NOT NULL AUTO_INCREMENT COMMENT '主键ID',
    `user_id` VARCHAR(255) DEFAULT NULL COMMENT 'user_id',
    `openid` VARCHAR(255) DEFAULT NULL COMMENT 'openid',
    `unionid` VARCHAR(255) DEFAULT NULL COMMENT 'unionid',
    `app_type` VARCHAR(255) DEFAULT NULL COMMENT 'app_type',
    `nickname` VARCHAR(255) DEFAULT NULL COMMENT 'nickname',
    `avatar` VARCHAR(255) DEFAULT NULL COMMENT 'avatar',
    `bound_at` VARCHAR(255) DEFAULT NULL COMMENT 'bound_at',
    `last_login_at` VARCHAR(255) DEFAULT NULL COMMENT 'last_login_at',
    PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS `chat_message` (
    `id` BIGINT NOT NULL AUTO_INCREMENT COMMENT '主键ID',
    `session_id` VARCHAR(255) DEFAULT NULL COMMENT 'session_id',
    `user_id` VARCHAR(255) DEFAULT NULL COMMENT 'user_id',
    `role` VARCHAR(255) DEFAULT NULL COMMENT 'role',
    `content` VARCHAR(255) DEFAULT NULL COMMENT 'content',
    `tokens` VARCHAR(255) DEFAULT NULL COMMENT 'tokens',
    `finish_reason` VARCHAR(255) DEFAULT NULL COMMENT 'finish_reason',
    `error_message` VARCHAR(255) DEFAULT NULL COMMENT 'error_message',
    `created_at` VARCHAR(255) DEFAULT NULL COMMENT 'created_at',
    `deleted` VARCHAR(255) DEFAULT NULL COMMENT 'deleted',
    PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS `chat_session` (
    `id` BIGINT NOT NULL AUTO_INCREMENT COMMENT '主键ID',
    `user_id` VARCHAR(255) DEFAULT NULL COMMENT 'user_id',
    `title` VARCHAR(255) DEFAULT NULL COMMENT 'title',
    `model` VARCHAR(255) DEFAULT NULL COMMENT 'model',
    `system_prompt` VARCHAR(255) DEFAULT NULL COMMENT 'system_prompt',
    `temperature` VARCHAR(255) DEFAULT NULL COMMENT 'temperature',
    `status` VARCHAR(255) DEFAULT NULL COMMENT 'status',
    `message_count` VARCHAR(255) DEFAULT NULL COMMENT 'message_count',
    `last_message_at` VARCHAR(255) DEFAULT NULL COMMENT 'last_message_at',
    `tenant_id` VARCHAR(255) DEFAULT NULL COMMENT 'tenant_id',
    `created_at` VARCHAR(255) DEFAULT NULL COMMENT 'created_at',
    `updated_at` VARCHAR(255) DEFAULT NULL COMMENT 'updated_at',
    `deleted` VARCHAR(255) DEFAULT NULL COMMENT 'deleted',
    PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS `function_call_log` (
    `id` BIGINT NOT NULL AUTO_INCREMENT COMMENT '主键ID',
    `user_id` VARCHAR(255) DEFAULT NULL COMMENT 'user_id',
    `session_id` VARCHAR(255) DEFAULT NULL COMMENT 'session_id',
    `tool_name` VARCHAR(255) DEFAULT NULL COMMENT 'tool_name',
    `arguments` VARCHAR(255) DEFAULT NULL COMMENT 'arguments',
    `result` VARCHAR(255) DEFAULT NULL COMMENT 'result',
    `status` VARCHAR(255) DEFAULT NULL COMMENT 'status',
    `error_msg` VARCHAR(255) DEFAULT NULL COMMENT 'error_msg',
    `duration_ms` VARCHAR(255) DEFAULT NULL COMMENT 'duration_ms',
    `ip` VARCHAR(255) DEFAULT NULL COMMENT 'ip',
    `user_agent` VARCHAR(255) DEFAULT NULL COMMENT 'user_agent',
    `created_at` VARCHAR(255) DEFAULT NULL COMMENT 'created_at',
    PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS `function_tool` (
    `id` BIGINT NOT NULL AUTO_INCREMENT COMMENT '主键ID',
    `name` VARCHAR(255) DEFAULT NULL COMMENT 'name',
    `display_name` VARCHAR(255) DEFAULT NULL COMMENT 'display_name',
    `description` VARCHAR(255) DEFAULT NULL COMMENT 'description',
    `category` VARCHAR(255) DEFAULT NULL COMMENT 'category',
    `scope` VARCHAR(255) DEFAULT NULL COMMENT 'scope',
    `owner_id` VARCHAR(255) DEFAULT NULL COMMENT 'owner_id',
    `parameters` VARCHAR(255) DEFAULT NULL COMMENT 'parameters',
    `endpoint` VARCHAR(255) DEFAULT NULL COMMENT 'endpoint',
    `http_method` VARCHAR(255) DEFAULT NULL COMMENT 'http_method',
    `enabled` VARCHAR(255) DEFAULT NULL COMMENT 'enabled',
    `tags` VARCHAR(255) DEFAULT NULL COMMENT 'tags',
    `created_at` VARCHAR(255) DEFAULT NULL COMMENT 'created_at',
    `updated_at` VARCHAR(255) DEFAULT NULL COMMENT 'updated_at',
    `deleted` VARCHAR(255) DEFAULT NULL COMMENT 'deleted',
    PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS `model_battle_log` (
    `id` BIGINT NOT NULL AUTO_INCREMENT COMMENT '主键ID',
    `battle_id` VARCHAR(255) DEFAULT NULL COMMENT 'battle_id',
    `user_id` VARCHAR(255) DEFAULT NULL COMMENT 'user_id',
    `model_id` VARCHAR(255) DEFAULT NULL COMMENT 'model_id',
    `model_code` VARCHAR(255) DEFAULT NULL COMMENT 'model_code',
    `prompt` VARCHAR(255) DEFAULT NULL COMMENT 'prompt',
    `response` VARCHAR(255) DEFAULT NULL COMMENT 'response',
    `prompt_tokens` VARCHAR(255) DEFAULT NULL COMMENT 'prompt_tokens',
    `completion_tokens` VARCHAR(255) DEFAULT NULL COMMENT 'completion_tokens',
    `latency_ms` VARCHAR(255) DEFAULT NULL COMMENT 'latency_ms',
    `status` VARCHAR(255) DEFAULT NULL COMMENT 'status',
    `error_msg` VARCHAR(255) DEFAULT NULL COMMENT 'error_msg',
    `score` VARCHAR(255) DEFAULT NULL COMMENT 'score',
    `judge_model` VARCHAR(255) DEFAULT NULL COMMENT 'judge_model',
    `judge_reason` VARCHAR(255) DEFAULT NULL COMMENT 'judge_reason',
    `created_at` VARCHAR(255) DEFAULT NULL COMMENT 'created_at',
    PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS `model_config` (
    `id` BIGINT NOT NULL AUTO_INCREMENT COMMENT '主键ID',
    `provider_id` VARCHAR(255) DEFAULT NULL COMMENT 'provider_id',
    `model_code` VARCHAR(255) DEFAULT NULL COMMENT 'model_code',
    `display_name` VARCHAR(255) DEFAULT NULL COMMENT 'display_name',
    `max_context` VARCHAR(255) DEFAULT NULL COMMENT 'max_context',
    `max_output` VARCHAR(255) DEFAULT NULL COMMENT 'max_output',
    `input_price` VARCHAR(255) DEFAULT NULL COMMENT 'input_price',
    `output_price` VARCHAR(255) DEFAULT NULL COMMENT 'output_price',
    `supports_vision` VARCHAR(255) DEFAULT NULL COMMENT 'supports_vision',
    `supports_tools` VARCHAR(255) DEFAULT NULL COMMENT 'supports_tools',
    `supports_stream` VARCHAR(255) DEFAULT NULL COMMENT 'supports_stream',
    `enabled` VARCHAR(255) DEFAULT NULL COMMENT 'enabled',
    `sort` VARCHAR(255) DEFAULT NULL COMMENT 'sort',
    `description` VARCHAR(255) DEFAULT NULL COMMENT 'description',
    `created_at` VARCHAR(255) DEFAULT NULL COMMENT 'created_at',
    `updated_at` VARCHAR(255) DEFAULT NULL COMMENT 'updated_at',
    `deleted` VARCHAR(255) DEFAULT NULL COMMENT 'deleted',
    PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS `model_provider` (
    `id` BIGINT NOT NULL AUTO_INCREMENT COMMENT '主键ID',
    `code` VARCHAR(255) DEFAULT NULL COMMENT 'code',
    `name` VARCHAR(255) DEFAULT NULL COMMENT 'name',
    `base_url` VARCHAR(255) DEFAULT NULL COMMENT 'base_url',
    `api_key` VARCHAR(255) DEFAULT NULL COMMENT 'api_key',
    `protocol` VARCHAR(255) DEFAULT NULL COMMENT 'protocol',
    `enabled` VARCHAR(255) DEFAULT NULL COMMENT 'enabled',
    `sort` VARCHAR(255) DEFAULT NULL COMMENT 'sort',
    `description` VARCHAR(255) DEFAULT NULL COMMENT 'description',
    `created_at` VARCHAR(255) DEFAULT NULL COMMENT 'created_at',
    `updated_at` VARCHAR(255) DEFAULT NULL COMMENT 'updated_at',
    `deleted` VARCHAR(255) DEFAULT NULL COMMENT 'deleted',
    PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS `model_quota` (
    `id` BIGINT NOT NULL AUTO_INCREMENT COMMENT '主键ID',
    `user_id` VARCHAR(255) DEFAULT NULL COMMENT 'user_id',
    `model_id` VARCHAR(255) DEFAULT NULL COMMENT 'model_id',
    `quota_date` VARCHAR(255) DEFAULT NULL COMMENT 'quota_date',
    `used_tokens` VARCHAR(255) DEFAULT NULL COMMENT 'used_tokens',
    `used_requests` VARCHAR(255) DEFAULT NULL COMMENT 'used_requests',
    `limit_tokens` VARCHAR(255) DEFAULT NULL COMMENT 'limit_tokens',
    `limit_requests` VARCHAR(255) DEFAULT NULL COMMENT 'limit_requests',
    `created_at` VARCHAR(255) DEFAULT NULL COMMENT 'created_at',
    `updated_at` VARCHAR(255) DEFAULT NULL COMMENT 'updated_at',
    PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS `training_task` (
    `id` BIGINT NOT NULL AUTO_INCREMENT COMMENT '主键ID',
    `user_id` VARCHAR(255) DEFAULT NULL COMMENT 'user_id',
    `model_name` VARCHAR(255) DEFAULT NULL COMMENT 'model_name',
    `corpus_path` VARCHAR(255) DEFAULT NULL COMMENT 'corpus_path',
    `n_layer` VARCHAR(255) DEFAULT NULL COMMENT 'n_layer',
    `n_head` VARCHAR(255) DEFAULT NULL COMMENT 'n_head',
    `n_embd` VARCHAR(255) DEFAULT NULL COMMENT 'n_embd',
    `block_size` VARCHAR(255) DEFAULT NULL COMMENT 'block_size',
    `max_iters` VARCHAR(255) DEFAULT NULL COMMENT 'max_iters',
    `batch_size` VARCHAR(255) DEFAULT NULL COMMENT 'batch_size',
    `learning_rate` VARCHAR(255) DEFAULT NULL COMMENT 'learning_rate',
    `status` VARCHAR(255) DEFAULT NULL COMMENT 'status',
    `progress` VARCHAR(255) DEFAULT NULL COMMENT 'progress',
    `current_loss` VARCHAR(255) DEFAULT NULL COMMENT 'current_loss',
    `current_iter` VARCHAR(255) DEFAULT NULL COMMENT 'current_iter',
    `error_message` VARCHAR(255) DEFAULT NULL COMMENT 'error_message',
    `created_at` VARCHAR(255) DEFAULT NULL COMMENT 'created_at',
    `updated_at` VARCHAR(255) DEFAULT NULL COMMENT 'updated_at',
    `completed_at` VARCHAR(255) DEFAULT NULL COMMENT 'completed_at',
    PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS `alert_channel` (
    `id` BIGINT NOT NULL AUTO_INCREMENT COMMENT '主键ID',
    `name` VARCHAR(255) DEFAULT NULL COMMENT 'name',
    `channel_type` VARCHAR(255) DEFAULT NULL COMMENT 'channel_type',
    `type` VARCHAR(255) DEFAULT NULL COMMENT 'type',
    `target` VARCHAR(255) DEFAULT NULL COMMENT 'target',
    `config` VARCHAR(255) DEFAULT NULL COMMENT 'config',
    `enabled` VARCHAR(255) DEFAULT NULL COMMENT 'enabled',
    `priority` VARCHAR(255) DEFAULT NULL COMMENT 'priority',
    `description` VARCHAR(255) DEFAULT NULL COMMENT 'description',
    `template` VARCHAR(255) DEFAULT NULL COMMENT 'template',
    `created_by` VARCHAR(255) DEFAULT NULL COMMENT 'created_by',
    `created_at` VARCHAR(255) DEFAULT NULL COMMENT 'created_at',
    PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS `alert_event` (
    `id` BIGINT NOT NULL AUTO_INCREMENT COMMENT '主键ID',
    `rule_id` VARCHAR(255) DEFAULT NULL COMMENT 'rule_id',
    `rule_name` VARCHAR(255) DEFAULT NULL COMMENT 'rule_name',
    `severity` VARCHAR(255) DEFAULT NULL COMMENT 'severity',
    `metric_name` VARCHAR(255) DEFAULT NULL COMMENT 'metric_name',
    `metric_value` VARCHAR(255) DEFAULT NULL COMMENT 'metric_value',
    `threshold` VARCHAR(255) DEFAULT NULL COMMENT 'threshold',
    `message` VARCHAR(255) DEFAULT NULL COMMENT 'message',
    `status` VARCHAR(255) DEFAULT NULL COMMENT 'status',
    `fired_at` VARCHAR(255) DEFAULT NULL COMMENT 'fired_at',
    `resolved_at` VARCHAR(255) DEFAULT NULL COMMENT 'resolved_at',
    `acked_at` VARCHAR(255) DEFAULT NULL COMMENT 'acked_at',
    `acked_by` VARCHAR(255) DEFAULT NULL COMMENT 'acked_by',
    `duration` VARCHAR(255) DEFAULT NULL COMMENT 'duration',
    PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS `alert_rule` (
    `id` BIGINT NOT NULL AUTO_INCREMENT COMMENT '主键ID',
    `name` VARCHAR(255) DEFAULT NULL COMMENT 'name',
    `description` VARCHAR(255) DEFAULT NULL COMMENT 'description',
    `metric_name` VARCHAR(255) DEFAULT NULL COMMENT 'metric_name',
    `service` VARCHAR(255) DEFAULT NULL COMMENT 'service',
    `operator` VARCHAR(255) DEFAULT NULL COMMENT 'operator',
    `threshold` VARCHAR(255) DEFAULT NULL COMMENT 'threshold',
    `severity` VARCHAR(255) DEFAULT NULL COMMENT 'severity',
    `cooldown_minutes` VARCHAR(255) DEFAULT NULL COMMENT 'cooldown_minutes',
    `enabled` VARCHAR(255) DEFAULT NULL COMMENT 'enabled',
    `tags` VARCHAR(255) DEFAULT NULL COMMENT 'tags',
    `notify_channel` VARCHAR(255) DEFAULT NULL COMMENT 'notify_channel',
    `created_at` VARCHAR(255) DEFAULT NULL COMMENT 'created_at',
    `updated_at` VARCHAR(255) DEFAULT NULL COMMENT 'updated_at',
    PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS `metric_snapshot` (
    `id` BIGINT NOT NULL AUTO_INCREMENT COMMENT '主键ID',
    `service` VARCHAR(255) DEFAULT NULL COMMENT 'service',
    `metric_name` VARCHAR(255) DEFAULT NULL COMMENT 'metric_name',
    `metric_value` VARCHAR(255) DEFAULT NULL COMMENT 'metric_value',
    `tags` VARCHAR(255) DEFAULT NULL COMMENT 'tags',
    `recorded_at` VARCHAR(255) DEFAULT NULL COMMENT 'recorded_at',
    PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS `pipeline_node_log` (
    `id` BIGINT NOT NULL AUTO_INCREMENT COMMENT '主键ID',
    `run_id` VARCHAR(255) DEFAULT NULL COMMENT 'run_id',
    `node_id` VARCHAR(255) DEFAULT NULL COMMENT 'node_id',
    `node_type` VARCHAR(255) DEFAULT NULL COMMENT 'node_type',
    `node_name` VARCHAR(255) DEFAULT NULL COMMENT 'node_name',
    `status` VARCHAR(255) DEFAULT NULL COMMENT 'status',
    `start_time` VARCHAR(255) DEFAULT NULL COMMENT 'start_time',
    `end_time` VARCHAR(255) DEFAULT NULL COMMENT 'end_time',
    `duration_ms` VARCHAR(255) DEFAULT NULL COMMENT 'duration_ms',
    `input_rows` VARCHAR(255) DEFAULT NULL COMMENT 'input_rows',
    `output_rows` VARCHAR(255) DEFAULT NULL COMMENT 'output_rows',
    `output_preview` VARCHAR(255) DEFAULT NULL COMMENT 'output_preview',
    `error_message` VARCHAR(255) DEFAULT NULL COMMENT 'error_message',
    `config_snapshot` VARCHAR(255) DEFAULT NULL COMMENT 'config_snapshot',
    PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS `pipeline_run` (
    `id` BIGINT NOT NULL AUTO_INCREMENT COMMENT '主键ID',
    `workflow_id` VARCHAR(255) DEFAULT NULL COMMENT 'workflow_id',
    `workflow_name` VARCHAR(255) DEFAULT NULL COMMENT 'workflow_name',
    `status` VARCHAR(255) DEFAULT NULL COMMENT 'status',
    `trigger_by` VARCHAR(255) DEFAULT NULL COMMENT 'trigger_by',
    `trigger_type` VARCHAR(255) DEFAULT NULL COMMENT 'trigger_type',
    `definition_snapshot` VARCHAR(255) DEFAULT NULL COMMENT 'definition_snapshot',
    `start_time` VARCHAR(255) DEFAULT NULL COMMENT 'start_time',
    `end_time` VARCHAR(255) DEFAULT NULL COMMENT 'end_time',
    `duration_ms` VARCHAR(255) DEFAULT NULL COMMENT 'duration_ms',
    `error_message` VARCHAR(255) DEFAULT NULL COMMENT 'error_message',
    `result_summary` VARCHAR(255) DEFAULT NULL COMMENT 'result_summary',
    `create_time` VARCHAR(255) DEFAULT NULL COMMENT 'create_time',
    PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS `pipeline_workflow` (
    `id` BIGINT NOT NULL AUTO_INCREMENT COMMENT '主键ID',
    `name` VARCHAR(255) DEFAULT NULL COMMENT 'name',
    `description` VARCHAR(255) DEFAULT NULL COMMENT 'description',
    `definition` VARCHAR(255) DEFAULT NULL COMMENT 'definition',
    `version` VARCHAR(255) DEFAULT NULL COMMENT 'version',
    `status` VARCHAR(255) DEFAULT NULL COMMENT 'status',
    `create_by` VARCHAR(255) DEFAULT NULL COMMENT 'create_by',
    `update_by` VARCHAR(255) DEFAULT NULL COMMENT 'update_by',
    `create_time` VARCHAR(255) DEFAULT NULL COMMENT 'create_time',
    `update_time` VARCHAR(255) DEFAULT NULL COMMENT 'update_time',
    `deleted` VARCHAR(255) DEFAULT NULL COMMENT 'deleted',
    PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS `pipeline_workflow_version` (
    `id` BIGINT NOT NULL AUTO_INCREMENT COMMENT '主键ID',
    `workflow_id` VARCHAR(255) DEFAULT NULL COMMENT 'workflow_id',
    `version` VARCHAR(255) DEFAULT NULL COMMENT 'version',
    `definition` VARCHAR(255) DEFAULT NULL COMMENT 'definition',
    `change_log` VARCHAR(255) DEFAULT NULL COMMENT 'change_log',
    `create_by` VARCHAR(255) DEFAULT NULL COMMENT 'create_by',
    `create_time` VARCHAR(255) DEFAULT NULL COMMENT 'create_time',
    PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS `prompt_template` (
    `id` BIGINT NOT NULL AUTO_INCREMENT COMMENT '主键ID',
    `name` VARCHAR(255) DEFAULT NULL COMMENT 'name',
    `description` VARCHAR(255) DEFAULT NULL COMMENT 'description',
    `category` VARCHAR(255) DEFAULT NULL COMMENT 'category',
    `content` VARCHAR(255) DEFAULT NULL COMMENT 'content',
    `variables` VARCHAR(255) DEFAULT NULL COMMENT 'variables',
    `creator_id` VARCHAR(255) DEFAULT NULL COMMENT 'creator_id',
    `creator_name` VARCHAR(255) DEFAULT NULL COMMENT 'creator_name',
    `is_public` VARCHAR(255) DEFAULT NULL COMMENT 'is_public',
    `use_count` VARCHAR(255) DEFAULT NULL COMMENT 'use_count',
    `created_at` VARCHAR(255) DEFAULT NULL COMMENT 'created_at',
    `updated_at` VARCHAR(255) DEFAULT NULL COMMENT 'updated_at',
    `deleted` VARCHAR(255) DEFAULT NULL COMMENT 'deleted',
    PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS `document` (
    `id` BIGINT NOT NULL AUTO_INCREMENT COMMENT '主键ID',
    `kb_id` VARCHAR(255) DEFAULT NULL COMMENT 'kb_id',
    `owner_id` VARCHAR(255) DEFAULT NULL COMMENT 'owner_id',
    `title` VARCHAR(255) DEFAULT NULL COMMENT 'title',
    `source_type` VARCHAR(255) DEFAULT NULL COMMENT 'source_type',
    `source_uri` VARCHAR(255) DEFAULT NULL COMMENT 'source_uri',
    `content` VARCHAR(255) DEFAULT NULL COMMENT 'content',
    `size_bytes` VARCHAR(255) DEFAULT NULL COMMENT 'size_bytes',
    `status` VARCHAR(255) DEFAULT NULL COMMENT 'status',
    `error_msg` VARCHAR(255) DEFAULT NULL COMMENT 'error_msg',
    `chunk_count` VARCHAR(255) DEFAULT NULL COMMENT 'chunk_count',
    `checksum` VARCHAR(255) DEFAULT NULL COMMENT 'checksum',
    `tags` VARCHAR(255) DEFAULT NULL COMMENT 'tags',
    `created_at` VARCHAR(255) DEFAULT NULL COMMENT 'created_at',
    `updated_at` VARCHAR(255) DEFAULT NULL COMMENT 'updated_at',
    `deleted` VARCHAR(255) DEFAULT NULL COMMENT 'deleted',
    PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS `document_chunk` (
    `id` BIGINT NOT NULL AUTO_INCREMENT COMMENT '主键ID',
    `doc_id` VARCHAR(255) DEFAULT NULL COMMENT 'doc_id',
    `kb_id` VARCHAR(255) DEFAULT NULL COMMENT 'kb_id',
    `owner_id` VARCHAR(255) DEFAULT NULL COMMENT 'owner_id',
    `chunk_index` VARCHAR(255) DEFAULT NULL COMMENT 'chunk_index',
    `content` VARCHAR(255) DEFAULT NULL COMMENT 'content',
    `embedding` VARCHAR(255) DEFAULT NULL COMMENT 'embedding',
    `dim` VARCHAR(255) DEFAULT NULL COMMENT 'dim',
    `char_count` VARCHAR(255) DEFAULT NULL COMMENT 'char_count',
    `start_pos` VARCHAR(255) DEFAULT NULL COMMENT 'start_pos',
    `end_pos` VARCHAR(255) DEFAULT NULL COMMENT 'end_pos',
    `access_count` VARCHAR(255) DEFAULT NULL COMMENT 'access_count',
    `last_access_at` VARCHAR(255) DEFAULT NULL COMMENT 'last_access_at',
    `created_at` VARCHAR(255) DEFAULT NULL COMMENT 'created_at',
    `updated_at` VARCHAR(255) DEFAULT NULL COMMENT 'updated_at',
    `deleted` VARCHAR(255) DEFAULT NULL COMMENT 'deleted',
    PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS `knowledge_base` (
    `id` BIGINT NOT NULL AUTO_INCREMENT COMMENT '主键ID',
    `owner_id` VARCHAR(255) DEFAULT NULL COMMENT 'owner_id',
    `tenant_id` VARCHAR(255) DEFAULT NULL COMMENT 'tenant_id',
    `name` VARCHAR(255) DEFAULT NULL COMMENT 'name',
    `description` VARCHAR(255) DEFAULT NULL COMMENT 'description',
    `visibility` VARCHAR(255) DEFAULT NULL COMMENT 'visibility',
    `doc_count` VARCHAR(255) DEFAULT NULL COMMENT 'doc_count',
    `chunk_count` VARCHAR(255) DEFAULT NULL COMMENT 'chunk_count',
    `tags` VARCHAR(255) DEFAULT NULL COMMENT 'tags',
    `created_at` VARCHAR(255) DEFAULT NULL COMMENT 'created_at',
    `updated_at` VARCHAR(255) DEFAULT NULL COMMENT 'updated_at',
    `deleted` VARCHAR(255) DEFAULT NULL COMMENT 'deleted',
    PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS `collab_message` (
    `id` BIGINT NOT NULL AUTO_INCREMENT COMMENT '主键ID',
    `room_id` VARCHAR(255) DEFAULT NULL COMMENT 'room_id',
    `user_id` VARCHAR(255) DEFAULT NULL COMMENT 'user_id',
    `username` VARCHAR(255) DEFAULT NULL COMMENT 'username',
    `nickname` VARCHAR(255) DEFAULT NULL COMMENT 'nickname',
    `type` VARCHAR(255) DEFAULT NULL COMMENT 'type',
    `content` VARCHAR(255) DEFAULT NULL COMMENT 'content',
    `metadata` VARCHAR(255) DEFAULT NULL COMMENT 'metadata',
    `client_msg_id` VARCHAR(255) DEFAULT NULL COMMENT 'client_msg_id',
    `broadcast` VARCHAR(255) DEFAULT NULL COMMENT 'broadcast',
    `created_at` VARCHAR(255) DEFAULT NULL COMMENT 'created_at',
    PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS `collab_participant` (
    `id` BIGINT NOT NULL AUTO_INCREMENT COMMENT '主键ID',
    `room_id` VARCHAR(255) DEFAULT NULL COMMENT 'room_id',
    `user_id` VARCHAR(255) DEFAULT NULL COMMENT 'user_id',
    `username` VARCHAR(255) DEFAULT NULL COMMENT 'username',
    `nickname` VARCHAR(255) DEFAULT NULL COMMENT 'nickname',
    `avatar` VARCHAR(255) DEFAULT NULL COMMENT 'avatar',
    `role` VARCHAR(255) DEFAULT NULL COMMENT 'role',
    `cursor_x` VARCHAR(255) DEFAULT NULL COMMENT 'cursor_x',
    `cursor_y` VARCHAR(255) DEFAULT NULL COMMENT 'cursor_y',
    `selection_id` VARCHAR(255) DEFAULT NULL COMMENT 'selection_id',
    `status` VARCHAR(255) DEFAULT NULL COMMENT 'status',
    `joined_at` VARCHAR(255) DEFAULT NULL COMMENT 'joined_at',
    `left_at` VARCHAR(255) DEFAULT NULL COMMENT 'left_at',
    `last_heartbeat` VARCHAR(255) DEFAULT NULL COMMENT 'last_heartbeat',
    PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS `collab_room` (
    `id` BIGINT NOT NULL AUTO_INCREMENT COMMENT '主键ID',
    `room_id` VARCHAR(255) DEFAULT NULL COMMENT 'room_id',
    `name` VARCHAR(255) DEFAULT NULL COMMENT 'name',
    `type` VARCHAR(255) DEFAULT NULL COMMENT 'type',
    `owner_id` VARCHAR(255) DEFAULT NULL COMMENT 'owner_id',
    `owner_name` VARCHAR(255) DEFAULT NULL COMMENT 'owner_name',
    `description` VARCHAR(255) DEFAULT NULL COMMENT 'description',
    `is_public` VARCHAR(255) DEFAULT NULL COMMENT 'is_public',
    `max_participants` VARCHAR(255) DEFAULT NULL COMMENT 'max_participants',
    `status` VARCHAR(255) DEFAULT NULL COMMENT 'status',
    `current_participants` VARCHAR(255) DEFAULT NULL COMMENT 'current_participants',
    `created_at` VARCHAR(255) DEFAULT NULL COMMENT 'created_at',
    `last_activity_at` VARCHAR(255) DEFAULT NULL COMMENT 'last_activity_at',
    `closed_at` VARCHAR(255) DEFAULT NULL COMMENT 'closed_at',
    PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

SET FOREIGN_KEY_CHECKS=1;