package com.minimax.ai.controller;

import lombok.RequiredArgsConstructor;
import lombok.extern.slf4j.Slf4j;
import org.springframework.web.bind.annotation.*;
import com.minimax.common.result.Result;
import com.minimax.common.result.Result;

import java.util.*;
import java.util.stream.Collectors;

/**
 * V6.3+ AI 智能填单 (AutoFill) 控制器
 *
 * <h2>职责</h2>
 * 根据表单类型 (formType) 和已有数据 (context), 推荐字段值
 * 用于前端"✨ 智能填充"按钮
 *
 * <h2>支持的 formType</h2>
 * - user: 用户创建
 * - apiKey: API Key 创建
 * - dataSource: 数据源配置
 * - pipeline: 流水线配置
 * - workflow: 工作流编排
 *
 * <h2>路由</h2>
 * - POST /api/v1/ai/autofill - 智能填单
 * - GET  /api/v1/ai/autofill/preview/{formType} - 一键预览示例
 * - GET  /api/v1/ai/autofill/recommend/{formType}/{field} - 字段推荐
 */
@Slf4j
@RestController
@RequestMapping("/api/v1/ai/autofill")
@RequiredArgsConstructor
public class AiAutoFillController {

    /**
     * 智能填单主接口
     *
     * @param req 包含 formType + context (已有数据)
     * @return 推荐字段值 Map
     */
    @PostMapping
    public Result<Map<String, Object>> autofill(@RequestBody AutoFillRequest req) {
        log.info("智能填单: formType={}, context={}", req.getFormType(), req.getContext());
        Map<String, Object> recommendations = switch (req.getFormType()) {
            case "user" -> recommendUser(req.getContext());
            case "apiKey" -> recommendApiKey(req.getContext());
            case "dataSource" -> recommendDataSource(req.getContext());
            case "pipeline" -> recommendPipeline(req.getContext());
            case "workflow" -> recommendWorkflow(req.getContext());
            default -> Map.of("error", "unknown formType: " + req.getFormType());
        };
        return Result.ok(recommendations);
    }

    /**
     * 一键预览: 给出完整示例数据
     */
    @GetMapping("/preview/{formType}")
    public Result<Map<String, Object>> preview(@PathVariable String formType) {
        log.info("一键预览: formType={}", formType);
        Map<String, Object> preview = switch (formType) {
            case "user" -> exampleUser();
            case "apiKey" -> exampleApiKey();
            case "dataSource" -> exampleDataSource();
            case "pipeline" -> examplePipeline();
            case "workflow" -> exampleWorkflow();
            default -> Map.of("error", "unknown formType: " + formType);
        };
        return Result.ok(preview);
    }

    /**
     * 字段推荐: Top-3 推荐值
     */
    @GetMapping("/recommend/{formType}/{field}")
    public Result<List<String>> recommend(@PathVariable String formType, @PathVariable String field) {
        log.info("字段推荐: formType={}, field={}", formType, field);
        List<String> recs = getTopRecommendations(formType, field);
        return Result.ok(recs);
    }

    // ============ 实现 (V6.3+ 用本地启发式, 后续可接 LLM) ============

    private Map<String, Object> recommendUser(Map<String, Object> ctx) {
        Map<String, Object> r = new LinkedHashMap<>();
        r.put("nickname", "新用户" + randomSuffix());
        r.put("email", "user" + randomSuffix() + "@liugl.ai");
        r.put("role", "USER");
        r.put("department", guessDepartment(ctx));
        r.put("status", "active");
        r.put("tags", List.of("新员工", "试用"));
        r.put("_confidence", 0.85);
        r.put("_source", "V6.3+ 本地启发式 (可接 LLM)");
        return r;
    }

    private Map<String, Object> recommendApiKey(Map<String, Object> ctx) {
        Map<String, Object> r = new LinkedHashMap<>();
        r.put("name", ctx.getOrDefault("purpose", "默认") + "-key-" + randomSuffix(4));
        r.put("scopes", List.of("read", "write"));
        r.put("expiresInDays", 90);
        r.put("rateLimit", 1000);
        r.put("ipWhitelist", List.of("*"));
        r.put("description", "Auto-generated by V6.3+ autofill");
        r.put("_confidence", 0.92);
        return r;
    }

    private Map<String, Object> recommendDataSource(Map<String, Object> ctx) {
        Map<String, Object> r = new LinkedHashMap<>();
        r.put("type", "mysql");
        r.put("host", "127.0.0.1");
        r.put("port", 3306);
        r.put("database", ctx.getOrDefault("database", "minimax_platform"));
        r.put("username", "readonly_user");
        r.put("connectionPoolSize", 10);
        r.put("timeout", 30);
        r.put("_confidence", 0.78);
        return r;
    }

    private Map<String, Object> recommendPipeline(Map<String, Object> ctx) {
        Map<String, Object> r = new LinkedHashMap<>();
        r.put("steps", List.of(
            Map.of("name", "fetch", "type", "http"),
            Map.of("name", "transform", "type", "script"),
            Map.of("name", "store", "type", "db")
        ));
        r.put("retryPolicy", "exponential");
        r.put("timeout", 60);
        r.put("_confidence", 0.80);
        return r;
    }

    private Map<String, Object> recommendWorkflow(Map<String, Object> ctx) {
        Map<String, Object> r = new LinkedHashMap<>();
        r.put("nodes", List.of(
            Map.of("id", "start", "type", "start"),
            Map.of("id", "ai-1", "type", "ai", "model", "minimax-chat"),
            Map.of("id", "end", "type", "end")
        ));
        r.put("edges", List.of(
            Map.of("from", "start", "to", "ai-1"),
            Map.of("from", "ai-1", "to", "end")
        ));
        r.put("_confidence", 0.75);
        return r;
    }

    private String guessDepartment(Map<String, Object> ctx) {
        Object hint = ctx.get("department");
        if (hint != null) return hint.toString();
        return "技术部";
    }

    private List<String> getTopRecommendations(String formType, String field) {
        return switch (formType + ":" + field) {
            case "user:role" -> List.of("USER", "OPERATOR", "ADMIN");
            case "user:department" -> List.of("技术部", "运营部", "财务部");
            case "apiKey:scopes" -> List.of("read", "write", "admin");
            case "dataSource:type" -> List.of("mysql", "mariadb", "postgresql");
            case "pipeline:retryPolicy" -> List.of("exponential", "linear", "fixed");
            default -> List.of("option1", "option2", "option3");
        };
    }

    private Map<String, Object> exampleUser() {
        Map<String, Object> r = new LinkedHashMap<>();
        r.put("username", "demo_user");
        r.put("nickname", "演示用户");
        r.put("email", "demo@liugl.ai");
        r.put("password", "Demo123!@#");
        r.put("role", "USER");
        r.put("department", "技术部");
        return r;
    }

    private Map<String, Object> exampleApiKey() {
        Map<String, Object> r = new LinkedHashMap<>();
        r.put("name", "demo-api-key");
        r.put("scopes", List.of("read", "write"));
        r.put("expiresInDays", 90);
        return r;
    }

    private Map<String, Object> exampleDataSource() {
        Map<String, Object> r = new LinkedHashMap<>();
        r.put("name", "demo-ds");
        r.put("type", "mysql");
        r.put("host", "127.0.0.1");
        r.put("port", 3306);
        return r;
    }

    private Map<String, Object> examplePipeline() {
        Map<String, Object> r = new LinkedHashMap<>();
        r.put("name", "demo-pipeline");
        r.put("steps", List.of("fetch", "transform", "store"));
        return r;
    }

    private Map<String, Object> exampleWorkflow() {
        Map<String, Object> r = new LinkedHashMap<>();
        r.put("name", "demo-workflow");
        r.put("nodes", List.of("start", "ai", "end"));
        return r;
    }

    private String randomSuffix() {
        return String.valueOf((int) (Math.random() * 9000) + 1000);
    }

    private String randomSuffix(int len) {
        String chars = "abcdefghijklmnopqrstuvwxyz0123456789";
        StringBuilder sb = new StringBuilder();
        Random r = new Random();
        for (int i = 0; i < len; i++) sb.append(chars.charAt(r.nextInt(chars.length())));
        return sb.toString();
    }

    // ============ DTO ============
    @lombok.Data
    public static class AutoFillRequest {
        private String formType;        // user / apiKey / dataSource / pipeline / workflow
        private Map<String, Object> context;  // 已有数据
    }
}
