server:
  port: 8095

spring:
  application:
    name: minimax-ws
  jackson:
    time-zone: GMT+8

minimax:
  jwt:
    secret: ${JWT_SECRET:VwSWPd816F4nwowFzF5B0F8rihlle2836g6QAh5i13o=}
    issuer: minimax-platform
